#line 2 "psl_input.c"

#line 4 "psl_input.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer psl_yy_create_buffer
#define yy_delete_buffer psl_yy_delete_buffer
#define yy_flex_debug psl_yy_flex_debug
#define yy_init_buffer psl_yy_init_buffer
#define yy_flush_buffer psl_yy_flush_buffer
#define yy_load_buffer_state psl_yy_load_buffer_state
#define yy_switch_to_buffer psl_yy_switch_to_buffer
#define yyin psl_yyin
#define yyleng psl_yyleng
#define yylex psl_yylex
#define yylineno psl_yylineno
#define yyout psl_yyout
#define yyrestart psl_yyrestart
#define yytext psl_yytext
#define yywrap psl_yywrap
#define yyalloc psl_yyalloc
#define yyrealloc psl_yyrealloc
#define yyfree psl_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE psl_yyrestart(psl_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int psl_yyleng;

extern FILE *psl_yyin, *psl_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE psl_yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-psl_yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < psl_yyleng; ++yyl )\
                    if ( psl_yytext[yyl] == '\n' )\
                        --psl_yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up psl_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up psl_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via psl_yyrestart()), so that the user can continue scanning by
	 * just pointing psl_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when psl_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int psl_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow psl_yywrap()'s to do buffer switches
 * instead of setting up a fresh psl_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void psl_yyrestart (FILE *input_file  );
void psl_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE psl_yy_create_buffer (FILE *file,int size  );
void psl_yy_delete_buffer (YY_BUFFER_STATE b  );
void psl_yy_flush_buffer (YY_BUFFER_STATE b  );
void psl_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void psl_yypop_buffer_state (void );

static void psl_yyensure_buffer_stack (void );
static void psl_yy_load_buffer_state (void );
static void psl_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER psl_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE psl_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE psl_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE psl_yy_scan_bytes (yyconst char *bytes,int len  );

void *psl_yyalloc (yy_size_t  );
void *psl_yyrealloc (void *,yy_size_t  );
void psl_yyfree (void *  );

#define yy_new_buffer psl_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        psl_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            psl_yy_create_buffer(psl_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        psl_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            psl_yy_create_buffer(psl_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define psl_yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *psl_yyin = (FILE *) 0, *psl_yyout = (FILE *) 0;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int psl_yylineno;

int psl_yylineno = 1;

extern char psl_yytext[];

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up psl_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	psl_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( psl_yyleng + (yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &psl_yytext[(yy_more_offset)], (yytext_ptr), psl_yyleng + 1 ); \
	psl_yyleng += (yy_more_offset); \
	(yy_prev_more_offset) = (yy_more_offset); \
	(yy_more_offset) = 0; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 116
#define YY_END_OF_BUFFER 117
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[362] =
    {   0,
        1,    1,  117,  115,  116,    1,  115,  116,    1,  116,
       38,  115,  116,   14,  115,  116,  103,  115,  116,  104,
      115,  116,   40,  115,  116,   41,  115,  116,  108,  115,
      116,   16,  115,  116,  114,  115,  116,   42,  115,  116,
      112,  115,  116,  110,  115,  116,  111,  115,  116,   21,
      115,  116,   35,  115,  116,   25,  115,  116,  109,  115,
      116,   67,  113,  115,  116,  113,  115,  116,   63,  113,
      115,  116,   57,  113,  115,  116,   56,  113,  115,  116,
      113,  115,  116,  113,  115,  116,   58,  113,  115,  116,
       59,  113,  115,  116,   55,  113,  115,  116,   48,  115,

      116,  107,  115,  116,   31,  115,  116,  113,  115,  116,
      113,  115,  116,  113,  115,  116,  113,  115,  116,  113,
      115,  116,  113,  115,  116,  113,  115,  116,  113,  115,
      116,  113,  115,  116,  113,  115,  116,  113,  115,  116,
      113,  115,  116,  113,  115,  116,  105,  115,  116,   12,
      115,  116,  106,  115,  116,   29,  115,  116,    1,   37,
       13,   39,    2,   15,  112,   19,   20,   34,   24,   23,
      113,   66,  113,   64,  113,   65,  113,   62,  113,   60,
      113,   61,  113,  113,    5,  113,  113,   54,   44,   45,
       30,  113,  113,  113,  113,  113,  113,  113,  113,   49,

      113,  113,  113,   51,  113,  113,  113,  113,  113,  113,
      113,   11,   28,   27,   26,   36,   17,   18,   33,   22,
      113,  113,   47,   46,  113,  113,  113,  113,  113,  113,
      113,  113,   43,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,   32,  113,    9,   10,  113,    3,  113,
      113,  113,  113,  113,  101,  113,  102,  113,  113,  113,
      113,  113,   91,  113,  113,  113,  113,  113,  113,  113,
        4,  113,  100,  113,  113,  113,  113,  113,  113,  113,
      113,   70,  113,   90,  113,  113,  113,   50,  113,   99,
      113,  113,  113,   69,  113,   95,  113,  113,  113,    6,

      113,    7,  113,  113,   87,  113,   89,  113,  113,  113,
       97,   98,  113,  113,   75,  113,   93,   94,  113,    8,
      113,  113,   53,  113,   86,   88,  113,   52,  113,  113,
       96,  113,   73,   74,  113,   92,  113,  113,   68,  113,
       79,  113,   72,  113,  113,   77,   78,  113,  113,   85,
      113,   76,   71,   84,  113,   81,  113,   83,  113,   80,
       82
    } ;

static yyconst flex_int16_t yy_accept[225] =
    {   0,
        1,    2,    3,    4,    6,    9,   11,   14,   17,   20,
       23,   26,   29,   32,   35,   38,   41,   44,   47,   50,
       53,   56,   59,   62,   66,   69,   73,   77,   81,   84,
       87,   91,   95,   99,  102,  105,  108,  111,  114,  117,
      120,  123,  126,  129,  132,  135,  138,  141,  144,  147,
      150,  153,  156,  159,  160,  161,  162,  163,  164,  165,
      166,  166,  167,  168,  169,  170,  171,  172,  174,  176,
      178,  180,  182,  184,  185,  187,  188,  189,  190,  190,
      190,  191,  192,  193,  194,  195,  196,  197,  198,  199,
      200,  202,  203,  204,  206,  207,  208,  209,  210,  211,

      212,  212,  212,  213,  214,  215,  216,  217,  218,  219,
      220,  221,  222,  223,  224,  225,  226,  227,  228,  229,
      230,  231,  232,  233,  235,  236,  237,  238,  239,  240,
      241,  242,  243,  244,  246,  247,  248,  249,  251,  252,
      253,  254,  255,  257,  259,  260,  261,  262,  263,  265,
      266,  267,  268,  269,  270,  271,  273,  275,  276,  277,
      278,  279,  280,  281,  282,  284,  285,  286,  287,  288,
      290,  292,  293,  294,  296,  298,  299,  300,  302,  304,
      305,  307,  309,  310,  311,  312,  314,  315,  317,  318,
      320,  322,  323,  325,  326,  327,  328,  330,  331,  332,

      333,  334,  336,  337,  338,  339,  341,  343,  344,  345,
      346,  347,  349,  350,  352,  353,  354,  355,  356,  358,
      360,  361,  362,  362
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    5,    1,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,   21,    1,   22,   23,   23,   23,   24,   25,
       26,   23,   27,   23,   23,   28,   23,   29,   23,   23,
       23,   30,   31,   32,   33,   23,   34,   35,   23,   23,
       36,    1,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   23,   23,   49,   50,   51,
       52,   53,   23,   54,   55,   56,   57,   58,   59,   60,
       61,   23,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[225] =
    {   0,
        0,    0,  241,  242,   64,   66,  221,  233,  242,  242,
      229,  242,  242,   58,  242,  242,  222,  242,  242,   61,
      217,   52,  242,   49,    0,   51,  213,    0,  205,  203,
        0,    0,  228,   73,  242,  166,   40,   43,  190,   33,
      177,  177,  175,  182,  171,   42,  173,   50,  171,  242,
       81,  242,   84,   99,  203,  242,  242,  242,  242,  206,
      200,  201,  242,  199,  242,  197,    0,    0,    0,    0,
        0,    0,    0,  188,    0,  182,  242,  242,  177,  193,
      242,  242,  160,  152,  165,  157,  153,  167,  162,  151,
        0,  161,   53,    0,  148,  150,   56,  153,  144,  145,

      178,  177,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  165,  171,  242,  242,  140,  153,  140,  142,  146,
      147,  137,  147,    0,  142,  141,  128,  139,  129,  129,
      132,  130,  131,    0,  242,  242,  153,    0,  120,  114,
      120,  129,    0,    0,  116,   54,  128,  116,  102,  126,
      124,  116,  117,  121,  116,    0,    0,  107,  117,  120,
      102,  109,   96,  110,    0,  242,   70,  109,  100,    0,
      103,  102,   98,    0,  104,   97,  106,    0,    0,  101,
      136,  105,   95,   82,   98,    0,   84,  111,   96,    0,
        0,   85,    0,  242,  242,   89,    0,   71,  242,   75,

       91,    0,  242,   80,   77,    0,  112,  242,   66,   70,
       86,    0,  120,  113,  242,  242,  242,   79,  117,  116,
      242,  242,  242,  116
    } ;

static yyconst flex_int16_t yy_def[225] =
    {   0,
      223,    1,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  223,  223,  223,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  223,  223,  223,  223,
      223,  223,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  224,  224,  223,  223,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  223,  223,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  223,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  223,  224,  224,  224,  223,  224,
      224,  224,  224,  223,  223,  224,  224,  224,  223,  224,

      223,  224,  223,  224,  224,  224,  224,  223,  224,  224,
      223,  224,  224,  224,  223,  223,  223,  224,  224,  224,
      223,  223,    0,  223
    } ;

static yyconst flex_int16_t yy_nxt[308] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   25,   25,   25,
       25,   30,   31,   32,   33,   34,   35,   36,   25,   37,
       38,   39,   25,   40,   41,   25,   25,   42,   25,   43,
       44,   45,   46,   25,   25,   25,   47,   25,   48,   49,
       25,   50,   51,   52,   53,   54,   54,   54,   54,   58,
       65,   66,   61,   68,   69,   71,   72,   59,   62,   63,
       83,   78,   79,   70,   80,   73,   85,   88,   84,  104,
       89,   81,  101,   95,   86,   96,   98,   99,  125,  102,

       54,   54,  162,  130,  163,  166,  185,  189,  195,  181,
      126,  131,  127,  182,  201,  211,  217,   67,  219,  222,
      221,  105,  220,  216,  215,  214,  213,  210,  209,  208,
      207,  206,  205,  204,  203,  200,  199,  198,  197,  194,
      167,  186,  190,  103,  193,  192,  106,  191,  188,  202,
      212,  218,  187,  184,  183,  180,  179,  178,  177,  176,
      175,  174,  196,  173,  172,  171,  170,  169,  168,  165,
      164,  161,  160,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  133,

      132,  129,  128,  124,  123,  122,  121,  120,  119,  118,
      117,  116,  115,  114,  113,  112,  111,  110,  109,  108,
       60,  107,  100,   97,   94,   93,   92,   91,   90,   87,
       82,   77,   76,   75,   74,   64,   60,   57,   56,   55,
      223,    3,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223
    } ;

static yyconst flex_int16_t yy_chk[308] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    6,    6,   14,
       22,   22,   20,   24,   24,   26,   26,   14,   20,   20,
       37,   34,   34,   24,   34,   26,   38,   40,   37,   53,
       40,   34,   51,   46,   38,   46,   48,   48,   93,   51,

       54,   54,  146,   97,  146,  149,  171,  175,  182,  167,
       93,   97,   93,  167,  188,  207,  214,  224,  218,  220,
      219,   53,  218,  213,  211,  210,  209,  205,  204,  201,
      200,  198,  196,  192,  189,  187,  185,  184,  183,  181,
      149,  171,  175,   51,  180,  177,   53,  176,  173,  188,
      207,  214,  172,  169,  168,  164,  163,  162,  161,  160,
      159,  158,  182,  155,  154,  153,  152,  151,  150,  148,
      147,  145,  142,  141,  140,  139,  137,  133,  132,  131,
      130,  129,  128,  127,  126,  125,  123,  122,  121,  120,
      119,  118,  117,  116,  113,  112,  102,  101,  100,   99,

       98,   96,   95,   92,   90,   89,   88,   87,   86,   85,
       84,   83,   80,   79,   76,   74,   66,   64,   62,   61,
       60,   55,   49,   47,   45,   44,   43,   42,   41,   39,
       36,   33,   30,   29,   27,   21,   17,   11,    8,    7,
        3,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[117] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

extern int psl_yy_flex_debug;
int psl_yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up psl_yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() ((yy_more_offset) = yy_flex_strlen( psl_yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(yy_more_offset) = (yy_prev_more_offset); \
	psl_yyleng -= (yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char psl_yytext[YYLMAX];
char *yytext_ptr;
#line 1 "psl_input.l"
/***************************************************************  -*-C-*-  ***/
#line 4 "psl_input.l"
/**CFile***********************************************************************

  FileName    [psl_input.l]

  PackageName [parser.psl]

  Synopsis    [Lexical analyzer for the PSL specification input language]

  SeeAlso     [psl_grammar.y]

  Author      [Roberto Cavada]

  Copyright   [
  This file is part of the ``parser.psl'' package of NuSMV version 2. 
  Copyright (C) 2005 by ITC-irst. 

  NuSMV version 2 is free software; you can redistribute it and/or 
  modify it under the terms of the GNU Lesser General Public 
  License as published by the Free Software Foundation; either 
  version 2 of the License, or (at your option) any later version.

  NuSMV version 2 is distributed in the hope that it will be useful, 
  but WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public 
  License along with this library; if not, write to the Free Software 
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA.

  For more information on NuSMV see <http://nusmv.irst.itc.it>
  or email to <nusmv-users@irst.itc.it>.
  Please report bugs to <nusmv-users@irst.itc.it>.

  To contact the NuSMV development board, email to <nusmv@irst.itc.it>. ]

******************************************************************************/

#include <stdio.h>
#include <errno.h>

#include "pslExpr.h"
#include "psl_grammar.h"

static char rcsid[] UTIL_UNUSED = "$Id: psl_input.l,v 1.1.2.21.6.1 2007/01/03 13:37:53 nusmv Exp $";

static int psl_skip_comment ARGS((void));
EXTERN void psl_yyerror ARGS((char* s, ...));

#define YY_INPUT(buf, result, max_size) \
	if ( YY_CURRENT_BUFFER->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for (n=0; n<max_size && \
		     (c = getc(psl_yyin)) != EOF && \
                     c!=' ' && c!='\n' && c!='\t' && c!='\r' && c!='\f'; ++n ) \
			buf[n] = (char) c; \
		if (c==' ' || c=='\n' || c=='\t' || c=='\r' || c=='\f') buf[n++] = (char) c; \
		if (c == EOF && ferror(psl_yyin)) YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, psl_yyin))==0 && ferror(psl_yyin)) \
			{ \
			if(errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(psl_yyin); \
			} \
		}


#line 784 "psl_input.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int psl_yylex_destroy (void );

int psl_yyget_debug (void );

void psl_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE psl_yyget_extra (void );

void psl_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *psl_yyget_in (void );

void psl_yyset_in  (FILE * in_str  );

FILE *psl_yyget_out (void );

void psl_yyset_out  (FILE * out_str  );

int psl_yyget_leng (void );

char *psl_yyget_text (void );

int psl_yyget_lineno (void );

void psl_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int psl_yywrap (void );
#else
extern int psl_yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( psl_yytext, psl_yyleng, 1, psl_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( psl_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( psl_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, psl_yyin))==0 && ferror(psl_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(psl_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int psl_yylex (void);

#define YY_DECL int psl_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after psl_yytext and psl_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 227 "psl_input.l"


#line 969 "psl_input.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)psl_yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in psl_yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! psl_yyin )
			psl_yyin = stdin;

		if ( ! psl_yyout )
			psl_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			psl_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				psl_yy_create_buffer(psl_yyin,YY_BUF_SIZE );
		}

		psl_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of psl_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 224 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 242 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_prev_more_offset); yyl < psl_yyleng; ++yyl )
				if ( psl_yytext[yyl] == '\n' )
					   
    psl_yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 229 "psl_input.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 230 "psl_input.l"
{ psl_skip_comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 231 "psl_input.l"
{ return TKTRUE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 232 "psl_input.l"
{ return TKFALSE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 234 "psl_input.l"
{ return TKINCONTEXT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 236 "psl_input.l"
{ psl_yylval.operator = TKFORALL; return TKFORALL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 237 "psl_input.l"
{ psl_yylval.operator = TKFORANY; return TKFORANY; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 238 "psl_input.l"
{ return TKBOOLEAN; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 240 "psl_input.l"
{ psl_yylval.operator = TKPIPEMINUSGT; return TKPIPEMINUSGT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 241 "psl_input.l"
{ psl_yylval.operator = TKPIPEEQGT; return TKPIPEEQGT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 242 "psl_input.l"
{ psl_yylval.operator = TKPIPEPIPE; return TKPIPEPIPE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 243 "psl_input.l"
{ psl_yylval.operator = TKPIPE; return TKPIPE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 245 "psl_input.l"
{ psl_yylval.operator = TKAMPERSANDAMPERSAND; return TKAMPERSANDAMPERSAND; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 246 "psl_input.l"
{ psl_yylval.operator = TKAMPERSAND; return TKAMPERSAND; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 248 "psl_input.l"
{ psl_yylval.operator = TKMINUSGT; return TKMINUSGT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 249 "psl_input.l"
{ psl_yylval.operator = TKMINUS; return TKMINUS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 251 "psl_input.l"
{ psl_yylval.operator = TKLTMINUSGT; return TKLTMINUSGT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 252 "psl_input.l"
{ psl_yylval.operator = TKLTLTLT; return TKLTLTLT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 253 "psl_input.l"
{ psl_yylval.operator = TKLTLT; return TKLTLT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 254 "psl_input.l"
{ psl_yylval.operator = TKLE; return TKLE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 255 "psl_input.l"
{ psl_yylval.operator = TKLT; return TKLT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 257 "psl_input.l"
{ psl_yylval.operator = TKGTGTGT; return TKGTGTGT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 258 "psl_input.l"
{ psl_yylval.operator = TKGTGT; return TKGTGT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 259 "psl_input.l"
{ psl_yylval.operator = TKGE; return TKGE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 260 "psl_input.l"
{ psl_yylval.operator = TKGT; return TKGT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 262 "psl_input.l"
{ psl_yylval.operator = TKTILDEPIPE; return TKTILDEPIPE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 263 "psl_input.l"
{ psl_yylval.operator = TKTILDECARET; return TKTILDECARET; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 264 "psl_input.l"
{ psl_yylval.operator = TKTILDEAMPERSAND; return TKTILDEAMPERSAND; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 265 "psl_input.l"
{ psl_yylval.operator = TKTILDE; return TKTILDE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 267 "psl_input.l"
{ psl_yylval.operator = TKCARETTILDE; return TKCARETTILDE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 268 "psl_input.l"
{ psl_yylval.operator = TKCARET; return TKCARET; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 269 "psl_input.l"
{ psl_yylval.operator = TKXOR; return TKXOR; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 271 "psl_input.l"
{ psl_yylval.operator = TKEQEQEQ; return TKEQEQEQ; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 272 "psl_input.l"
{ psl_yylval.operator = TKEQEQ; return TKEQEQ; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 273 "psl_input.l"
{ psl_yylval.operator = TKEQ; return TKEQ; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 275 "psl_input.l"
{ psl_yylval.operator = TKBANGEQEQ; return TKBANGEQEQ; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 276 "psl_input.l"
{ psl_yylval.operator = TKBANGEQ; return TKBANGEQ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 277 "psl_input.l"
{ psl_yylval.operator = TKBANG; return TKBANG; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 279 "psl_input.l"
{ psl_yylval.operator = TKSPLATSPLAT; return TKSPLATSPLAT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 280 "psl_input.l"
{ psl_yylval.operator = TKSPLAT; return TKSPLAT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 282 "psl_input.l"
{ psl_yylval.operator = TKPLUS; return TKPLUS; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 283 "psl_input.l"
{ psl_yylval.operator = TKSLASH; return TKSLASH; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 284 "psl_input.l"
{ psl_yylval.operator = TKPERCENT; return TKPERCENT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 286 "psl_input.l"
{ psl_yylval.operator = TKLBSPLAT; return TKLBSPLAT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 287 "psl_input.l"
{ psl_yylval.operator = TKLBEQ; return TKLBEQ; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 288 "psl_input.l"
{ psl_yylval.operator = TKLBMINUSGT; return TKLBMINUSGT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 289 "psl_input.l"
{ psl_yylval.operator = TKLBPLUSRB; return TKLBPLUSRB; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 290 "psl_input.l"
{ return TKLB; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 292 "psl_input.l"
{ psl_yylval.operator = TKIN; return TKIN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 293 "psl_input.l"
{ psl_yylval.operator = TKUNION; return TKUNION; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 294 "psl_input.l"
{ return TKOR; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 295 "psl_input.l"
{ return TKPOSEDGE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 296 "psl_input.l"
{ return TKNEGEDGE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 298 "psl_input.l"
{ psl_yylval.operator = TKXBANG; return TKXBANG; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 299 "psl_input.l"
{ psl_yylval.operator = TKX; return TKX; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 301 "psl_input.l"
{ psl_yylval.operator = TKG; return TKG; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 302 "psl_input.l"
{ psl_yylval.operator = TKF; return TKF; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 303 "psl_input.l"
{ psl_yylval.operator = TKU; return TKU; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 304 "psl_input.l"
{ psl_yylval.operator = TKW; return TKW; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 306 "psl_input.l"
{ psl_yylval.operator = TKEG; return TKEG; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 307 "psl_input.l"
{ psl_yylval.operator = TKEX; return TKEX; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 308 "psl_input.l"
{ psl_yylval.operator = TKEF; return TKEF; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 309 "psl_input.l"
{ psl_yylval.operator = TKE; return TKE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 311 "psl_input.l"
{ psl_yylval.operator = TKAG; return TKAG; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 312 "psl_input.l"
{ psl_yylval.operator = TKAX; return TKAX; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 313 "psl_input.l"
{ psl_yylval.operator = TKAF; return TKAF; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 314 "psl_input.l"
{ psl_yylval.operator = TKA; return TKA; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 316 "psl_input.l"
{ return TKPROPERTY; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 318 "psl_input.l"
{ psl_yylval.operator = TKALWAYS; return TKALWAYS; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 319 "psl_input.l"
{ psl_yylval.operator = TKNEVER; return TKNEVER; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 320 "psl_input.l"
{ psl_yylval.operator = TKEVENTUALLYBANG; return TKEVENTUALLYBANG; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 323 "psl_input.l"
{ psl_yylval.operator = TKWITHINBANG_; return TKWITHINBANG_; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 324 "psl_input.l"
{ psl_yylval.operator = TKWITHINBANG; return TKWITHINBANG; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 325 "psl_input.l"
{ psl_yylval.operator = TKWITHIN_; return TKWITHIN_; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 326 "psl_input.l"
{ psl_yylval.operator = TKWITHIN; return TKWITHIN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 328 "psl_input.l"
{ psl_yylval.operator = TKWHILENOTBANG_; return TKWHILENOTBANG_; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 329 "psl_input.l"
{ psl_yylval.operator = TKWHILENOTBANG; return TKWHILENOTBANG; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 330 "psl_input.l"
{ psl_yylval.operator = TKWHILENOT_; return TKWHILENOT_; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 331 "psl_input.l"
{ psl_yylval.operator = TKWHILENOT; return TKWHILENOT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 333 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENT_ABANG; return TKNEXT_EVENT_ABANG; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 334 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENT_A; return TKNEXT_EVENT_A; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 335 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENT_EBANG; return TKNEXT_EVENT_EBANG; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 336 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENT_E; return TKNEXT_EVENT_E; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 337 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENTBANG; return TKNEXT_EVENTBANG; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 338 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENT; return TKNEXT_EVENT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 339 "psl_input.l"
{ psl_yylval.operator = TKNEXT_ABANG; return TKNEXT_ABANG; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 340 "psl_input.l"
{ psl_yylval.operator = TKNEXT_A; return TKNEXT_A; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 341 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EBANG; return TKNEXT_EBANG; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 342 "psl_input.l"
{ psl_yylval.operator = TKNEXT_E; return TKNEXT_E; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 343 "psl_input.l"
{ psl_yylval.operator = TKNEXTBANG; return TKNEXTBANG; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 344 "psl_input.l"
{ psl_yylval.operator = TKNEXT; return TKNEXT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 346 "psl_input.l"
{ psl_yylval.operator = TKBEFOREBANG_; return TKBEFOREBANG_; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 347 "psl_input.l"
{ psl_yylval.operator = TKBEFOREBANG; return TKBEFOREBANG; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 348 "psl_input.l"
{ psl_yylval.operator = TKBEFORE_; return TKBEFORE_; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 349 "psl_input.l"
{ psl_yylval.operator = TKBEFORE; return TKBEFORE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 351 "psl_input.l"
{ psl_yylval.operator = TKUNTILBANG_; return TKUNTILBANG_; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 352 "psl_input.l"
{ psl_yylval.operator = TKUNTILBANG; return TKUNTILBANG; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 353 "psl_input.l"
{ psl_yylval.operator = TKUNTIL_; return TKUNTIL_; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 354 "psl_input.l"
{ psl_yylval.operator = TKUNTIL; return TKUNTIL; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 356 "psl_input.l"
{ return TKABORT; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 358 "psl_input.l"
{ return TKCASE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 359 "psl_input.l"
{ return TKENDCASE; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 361 "psl_input.l"
{ return TKLP; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 362 "psl_input.l"
{ return TKRP; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 363 "psl_input.l"
{ return TKLC; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 364 "psl_input.l"
{ return TKRC; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 365 "psl_input.l"
{ return TKRB; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 366 "psl_input.l"
{ return TKCOMMA; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 367 "psl_input.l"
{ return TKQUESTIONMARK; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 368 "psl_input.l"
{ return TKCOLON; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 369 "psl_input.l"
{ return TKSEMI; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 371 "psl_input.l"
{ psl_yylval.ival = atoi(psl_yytext); return TKNUMBER; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 373 "psl_input.l"
{ psl_yylval.idname=strdup(psl_yytext); return TKATOM; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 375 "psl_input.l"
{ return TKDOT; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 377 "psl_input.l"
{ return TKEOF; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 379 "psl_input.l"
{ psl_yyerror("Invalid character: %s", psl_yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 381 "psl_input.l"
ECHO;
	YY_BREAK
#line 1656 "psl_input.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed psl_yyin at a new source and called
			 * psl_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = psl_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( psl_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * psl_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of psl_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			psl_yyrestart(psl_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) psl_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 224 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 224 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 223);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up psl_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --psl_yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					psl_yyrestart(psl_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( psl_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve psl_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    psl_yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void psl_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        psl_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            psl_yy_create_buffer(psl_yyin,YY_BUF_SIZE );
	}

	psl_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	psl_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void psl_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		psl_yypop_buffer_state();
	 *		psl_yypush_buffer_state(new_buffer);
     */
	psl_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	psl_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (psl_yywrap()) processing, but the only time this flag
	 * is looked at is after psl_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void psl_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	psl_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE psl_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) psl_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in psl_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) psl_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in psl_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	psl_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with psl_yy_create_buffer()
 * 
 */
    void psl_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		psl_yyfree((void *) b->yy_ch_buf  );

	psl_yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a psl_yyrestart() or at EOF.
 */
    static void psl_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	psl_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then psl_yy_init_buffer was _probably_
     * called from psl_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 1;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void psl_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		psl_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void psl_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	psl_yyensure_buffer_stack();

	/* This block is copied from psl_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from psl_yy_switch_to_buffer. */
	psl_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void psl_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	psl_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		psl_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void psl_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)psl_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in psl_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)psl_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in psl_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE psl_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) psl_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in psl_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	psl_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to psl_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       psl_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE psl_yy_scan_string (yyconst char * yystr )
{
    
	return psl_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to psl_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE psl_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) psl_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in psl_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = psl_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in psl_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up psl_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		psl_yytext[psl_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = psl_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		psl_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int psl_yyget_lineno  (void)
{
        
    return psl_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *psl_yyget_in  (void)
{
        return psl_yyin;
}

/** Get the output stream.
 * 
 */
FILE *psl_yyget_out  (void)
{
        return psl_yyout;
}

/** Get the length of the current token.
 * 
 */
int psl_yyget_leng  (void)
{
        return psl_yyleng;
}

/** Get the current token.
 * 
 */

char *psl_yyget_text  (void)
{
        return psl_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void psl_yyset_lineno (int  line_number )
{
    
    psl_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see psl_yy_switch_to_buffer
 */
void psl_yyset_in (FILE *  in_str )
{
        psl_yyin = in_str ;
}

void psl_yyset_out (FILE *  out_str )
{
        psl_yyout = out_str ;
}

int psl_yyget_debug  (void)
{
        return psl_yy_flex_debug;
}

void psl_yyset_debug (int  bdebug )
{
        psl_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from psl_yylex_destroy(), so don't allocate here.
     */

    /* We do not touch psl_yylineno unless the option is enabled. */
    psl_yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    psl_yyin = stdin;
    psl_yyout = stdout;
#else
    psl_yyin = (FILE *) 0;
    psl_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * psl_yylex_init()
     */
    return 0;
}

/* psl_yylex_destroy is for both reentrant and non-reentrant scanners. */
int psl_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		psl_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		psl_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	psl_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    psl_yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * psl_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *psl_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *psl_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void psl_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see psl_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 381 "psl_input.l"



static int psl_skip_comment() 
{
  register int c;

  do { c = input(); } while ( c != '\n' && c != EOF );
  return 0;
}

