#line 2 "chkLex.c"

#line 4 "chkLex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer chk_create_buffer
#define yy_delete_buffer chk_delete_buffer
#define yy_flex_debug chk_flex_debug
#define yy_init_buffer chk_init_buffer
#define yy_flush_buffer chk_flush_buffer
#define yy_load_buffer_state chk_load_buffer_state
#define yy_switch_to_buffer chk_switch_to_buffer
#define yyin chkin
#define yyleng chkleng
#define yylex chklex
#define yylineno chklineno
#define yyout chkout
#define yyrestart chkrestart
#define yytext chktext
#define yywrap chkwrap
#define yyalloc chkalloc
#define yyrealloc chkrealloc
#define yyfree chkfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE chkrestart(chkin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int chkleng;

extern FILE *chkin, *chkout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up chktext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up chktext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via chkrestart()), so that the user can continue scanning by
	 * just pointing chkin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when chktext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int chkleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow chkwrap()'s to do buffer switches
 * instead of setting up a fresh chkin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void chkrestart (FILE *input_file  );
void chk_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE chk_create_buffer (FILE *file,int size  );
void chk_delete_buffer (YY_BUFFER_STATE b  );
void chk_flush_buffer (YY_BUFFER_STATE b  );
void chkpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void chkpop_buffer_state (void );

static void chkensure_buffer_stack (void );
static void chk_load_buffer_state (void );
static void chk_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER chk_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE chk_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE chk_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE chk_scan_bytes (yyconst char *bytes,int len  );

void *chkalloc (yy_size_t  );
void *chkrealloc (void *,yy_size_t  );
void chkfree (void *  );

#define yy_new_buffer chk_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        chkensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            chk_create_buffer(chkin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        chkensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            chk_create_buffer(chkin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define chkwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *chkin = (FILE *) 0, *chkout = (FILE *) 0;

typedef int yy_state_type;

extern int chklineno;

int chklineno = 1;

extern char *chktext;
#define yytext_ptr chktext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up chktext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	chkleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[173] =
    {   0,
        0,    0,   38,   35,   27,   36,   22,   14,   25,   23,
       24,   25,   28,   25,   31,   34,   33,   25,   26,   25,
       18,   18,   13,   10,   12,   11,   19,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   29,   25,   32,   19,
       21,    0,   31,   19,    0,   30,   18,    0,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       20,    0,    1,    0,   17,    4,   18,   18,   18,   18,
       18,   18,    9,   18,   18,   18,   18,   18,   18,   17,
       18,   18,   18,   18,    2,   18,   18,    5,   18,   18,
        8,   18,   18,    0,   30,   18,   18,   18,   18,   18,

       18,   18,    0,   16,   16,   16,   16,   16,   16,    3,
       18,   18,   18,   18,   18,    0,   16,   15,    0,   16,
       16,    0,   16,    0,   16,   16,   16,   16,   16,    0,
        0,   30,   18,   18,   18,   18,    0,    0,   16,   16,
       16,   16,   16,   16,   18,   18,   18,    0,   16,    0,
       16,   16,   16,    0,   16,   16,   16,   16,   16,    0,
       18,    7,    9,    0,   18,    0,   18,   18,   18,   18,
        6,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    7,    8,    9,
       10,   11,   11,   12,   11,    8,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,    1,    1,   20,   21,   21,   21,   21,   22,
       23,   21,   21,   21,   21,   24,   21,   21,   21,   21,
       21,   21,   21,   21,   25,   21,   21,   26,   21,   21,
        8,    1,    8,   27,   28,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   21,   38,   39,   40,   41,
       42,   43,   21,   44,   45,   46,   47,   48,   21,   21,
       21,   21,   49,   50,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[52] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    4,    1,    1,
        1,    1,    5,    6,    1,    1,    1,    7,    1,    8,
        8,    8,    8,    8,    8,    8,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    2,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[196] =
    {   0,
        0,    0,  133,  997,  997,  997,  113,  997,  121,  997,
      997,  997,  997,  113,  111,  997,  997,   35,   95,   36,
       52,   53,   54,   55,   70,   71,  997,   73,   86,   88,
       89,  101,  116,  119,   98,  103,  997,   61,  997,  997,
      997,  107,   94,   81,   94,   99,  111,   91,  123,  130,
      118,  134,  138,  145,  146,  158,  153,  163,  165,  175,
      997,   84,  997,   81,    0,  176,  177,  193,  188,  189,
      200,  201,  205,  212,  219,  226,  224,  231,  241,    0,
      242,  249,  257,  262,  261,  272,  273,  277,  290,  289,
      285,  297,  304,  335,  338,  341,  324,  326,  325,  336,

      337,  351,  382,  114,  362,  388,  436,  408,  484,  356,
      387,  405,  386,  388,  361,  148,  201,  997,  454,  289,
      460,  441,  476,  497,  503,  551,  518,  536,  599,  385,
      510,  558,  569,  409,  450,  504,   41,  514,  411,  576,
      606,  654,  624,  702,  538,  590,  559,   34,  459,  636,
      464,  637,  662,  675,  694,  750,  721,  724,  798,  533,
      628,  641,  997,   28,  662,   18,  690,  703,  698,  710,
      723,  997,  845,  853,  859,  865,  868,  874,  880,  886,
      893,  900,  907,  914,  921,  928,  934,  940,  946,  953,
      960,  967,  974,  981,  988

    } ;

static yyconst flex_int16_t yy_def[196] =
    {   0,
      172,    1,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      173,  173,  173,  173,  173,  173,  172,  173,  173,  173,
      173,  173,  173,  173,   34,   34,  172,  172,  172,  172,
      172,  174,  172,  172,  172,  175,   34,  176,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
      172,  174,  172,  176,  177,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,  177,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,  178,  179,  180,   34,   34,   34,   34,

       34,   34,  178,  181,  182,  183,  184,  185,  186,   34,
       34,   34,   34,   34,   34,  172,  181,  172,  178,  181,
      182,  172,  183,  178,  183,  184,  185,  185,  186,  172,
      187,  188,  189,   34,   34,   34,  172,  187,  190,  191,
      192,  193,  194,  195,   34,   34,   34,  172,  190,  187,
      190,  191,  192,  187,  192,  193,  194,  194,  195,  172,
       34,   34,  172,  172,   34,  172,   34,   34,   34,   34,
       34,    0,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172

    } ;

static yyconst flex_int16_t yy_nxt[1049] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    4,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   22,   25,   26,   27,   22,   22,   28,
       29,   30,   31,   22,   22,   22,   32,   22,   22,   33,
       22,   22,   22,   22,   34,   22,   35,   36,   37,   38,
       39,   40,   44,   40,   40,   45,   45,   45,   45,   46,
       46,   46,   46,  163,   46,   46,   46,   46,  166,   48,
       48,   48,   48,   45,   45,   49,   45,   46,   46,  163,
       46,  148,   46,   46,   64,   46,   63,   48,   48,   45,
       48,   45,   45,   46,   64,   46,   46,   45,   46,   40,

       46,   46,   45,   48,   45,   48,   48,   43,   46,   63,
       61,   48,   40,   46,   50,  116,   48,  116,   48,   45,
       52,   51,   45,   46,   43,   42,   46,   41,   46,   53,
       40,   46,  172,   48,   47,  172,   48,  172,   59,   47,
       47,   54,  172,   47,   60,   47,   66,   47,   47,  116,
       68,  116,  172,   47,   47,   56,   47,   55,  172,   47,
       47,   57,  118,   47,   58,   47,   47,   69,   47,   70,
       47,   67,   47,  172,   47,   47,   47,   74,  172,   47,
       47,   72,   47,   47,   71,   76,  172,   47,   47,   47,
       73,   47,   75,  172,   47,   47,  118,  172,   47,   47,

       47,   47,  116,   47,  116,   47,   77,   47,   47,   78,
       47,   79,   47,   47,  172,   73,   83,   47,   47,   47,
       47,   47,   47,   81,   82,   47,  172,  172,  172,   47,
       47,   47,  172,   47,   47,   47,   47,   47,   47,   84,
      172,   47,   47,   47,  172,   47,   85,   47,   47,  118,
       47,  172,  172,  172,   47,   47,   88,   47,   86,   87,
       47,   47,   47,  172,   47,   94,   47,   90,   47,   47,
       89,   47,   73,   47,   95,  172,   47,   47,   47,   91,
      172,  172,  172,   47,   47,   47,   47,   47,   93,   92,
      116,   47,  116,   47,   47,  172,  172,   47,   47,   47,

      172,  172,   47,   47,   47,   98,   47,   96,   47,   47,
       97,  172,  172,   47,   47,   47,  172,   47,   47,   47,
       99,   47,   47,  100,  172,   47,   47,   47,  172,  101,
       47,   47,   47,   47,   47,   47,  102,  118,   94,   47,
       47,   94,   47,  172,   94,   46,   47,  103,   46,   47,
       95,   46,   48,   95,   47,   48,  110,  111,   48,  172,
       47,   47,   47,  116,  114,  119,   47,   47,   47,   47,
      112,   47,   47,   47,  103,  117,  113,  172,   47,   47,
      105,   47,   47,  107,  115,  103,  109,   47,   45,  116,
      130,  122,   47,   47,  103,   46,   47,  136,   47,  172,

       46,   47,   48,   47,  172,   48,   47,  121,  131,  116,
      118,  122,  116,  172,  116,   46,  172,  132,  134,  172,
       46,  137,   47,   47,   47,   48,  135,  105,   47,   47,
       47,   47,   47,   47,  172,  172,  118,  116,  172,  124,
      145,   47,  116,   46,  122,   47,  172,   47,   95,  123,
      133,   47,  172,   48,   47,  116,  118,  119,   48,  118,
      116,  116,  116,  119,  172,  116,  103,  116,  172,  172,
      172,  172,  103,  117,  172,  172,  172,  116,  146,  122,
      172,  126,  172,   46,  118,  116,   47,  124,   46,  118,
      172,   46,   47,   48,  172,   47,   95,  127,  116,  105,

      124,   48,  118,  172,  116,  121,  122,  118,  118,  103,
       46,  172,  118,  131,   48,   46,  172,  138,  172,  116,
       48,  122,  138,  172,  118,   46,  138,   48,  172,  129,
       46,  172,  118,  172,  172,   48,   45,  116,  172,  122,
       47,  160,  105,   46,  147,  118,   47,  172,   46,   47,
       48,  118,  116,   48,  124,  140,  172,  172,   46,  140,
      172,  131,  172,   95,  123,   46,  118,  172,   48,  164,
      132,   46,  131,  172,   47,   48,   46,  116,  172,  150,
       47,  132,   47,   47,  118,  172,   48,  172,  138,  149,
      172,  162,  172,  172,  172,   47,  126,  172,  172,  118,

      116,   47,  124,  142,   47,  172,   46,  116,  172,  122,
      172,   95,  127,   46,  144,  172,   48,  172,   46,  172,
      172,  152,  172,   48,  118,  116,   47,  122,  172,  172,
      161,   46,   47,  172,  172,   47,   46,  116,  116,  150,
      150,   48,  172,  172,  129,  172,  172,  118,  138,  138,
      149,  172,  172,  172,  118,  116,  172,  154,  172,  172,
      172,   46,  165,  116,   47,  122,  132,  153,  172,   46,
       47,   48,  118,   47,   46,  172,  116,   47,  154,   48,
      172,  140,  152,   47,  118,  118,   47,  138,  172,  172,
      172,  172,   48,  172,  172,  116,  172,  122,   47,  156,

      172,   46,  118,  116,   47,  154,   46,   47,  167,   46,
      118,   48,  172,  172,  132,  157,  172,  172,  168,   48,
      140,  172,  116,  118,  122,  116,   47,  122,   46,  172,
      170,   46,   47,   46,   47,   47,   46,  169,   48,   47,
       47,   48,  118,   47,  172,   47,   47,  159,   47,  172,
      118,  116,   47,  154,  171,   47,  172,   46,  172,   47,
      172,  172,  132,  153,  172,   47,  172,   48,   47,  118,
      172,  172,  118,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  156,  172,  172,  118,  116,

      172,  154,  172,  172,  172,   46,  172,  172,  172,  172,
      132,  157,  172,  172,  172,   48,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  159,  172,  172,  118,   47,   47,   47,
       47,   47,   47,   62,   62,   62,   62,   62,   62,   62,
       62,   46,   46,   46,   46,   46,   46,   65,  172,  172,
      172,  172,   65,   80,  172,   80,  104,  172,  104,  172,
      104,  104,  106,  106,  106,  106,  106,  106,  108,  108,
      108,  108,  108,  108,  117,  117,  172,  172,  117,  172,

      117,  120,  120,  172,  120,  120,  172,  120,  123,  123,
      123,  123,  123,  123,  123,  125,  125,  125,  125,  125,
      125,  125,  127,  127,  127,  127,  127,  127,  127,  128,
      128,  128,  128,  128,  128,  128,  139,  172,  139,  172,
      139,  139,  141,  141,  141,  141,  141,  141,  143,  143,
      143,  143,  143,  143,  149,  149,  172,  172,  149,  172,
      149,  151,  151,  172,  151,  151,  172,  151,  153,  153,
      153,  153,  153,  153,  153,  155,  155,  155,  155,  155,
      155,  155,  157,  157,  157,  157,  157,  157,  157,  158,
      158,  158,  158,  158,  158,  158,    3,  172,  172,  172,

      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172
    } ;

static yyconst flex_int16_t yy_chk[1049] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   18,   18,   20,   20,   21,   22,   23,   24,   21,
       22,   23,   24,  166,   21,   22,   23,   24,  164,   21,
       22,   23,   24,   25,   26,   21,   28,   25,   26,  148,
       28,  137,   25,   26,   64,   28,   62,   25,   26,   29,
       28,   30,   31,   29,   48,   30,   31,   45,   29,   44,

       30,   31,   46,   29,   32,   30,   31,   43,   32,   42,
       38,   45,   19,   32,   28,  104,   46,  104,   32,   33,
       30,   29,   34,   33,   15,   14,   34,    9,   33,   31,
        7,   34,    3,   33,   35,    0,   34,    0,   35,   36,
       35,   32,    0,   35,   36,   36,   49,   47,   36,  116,
       51,  116,    0,   47,   51,   34,   47,   33,    0,   49,
       51,   34,  104,   51,   34,   49,   50,   52,   49,   53,
       52,   50,   50,    0,   53,   50,   52,   55,    0,   52,
       53,   54,   55,   53,   53,   57,    0,   54,   55,   57,
       54,   55,   56,    0,   56,   57,  116,    0,   57,   58,

       56,   59,  117,   56,  117,   58,   58,   59,   58,   59,
       59,   60,   66,   67,    0,   67,   70,   60,   66,   67,
       60,   66,   67,   68,   69,   70,    0,    0,    0,   68,
       69,   70,    0,   69,   70,   68,   71,   72,   68,   71,
        0,   73,   71,   72,    0,   71,   72,   73,   74,  117,
       73,    0,    0,    0,   74,   75,   76,   74,   74,   75,
       77,   75,   76,    0,   75,   84,   77,   78,   76,   77,
       77,   76,   79,   78,   84,    0,   78,   79,   81,   81,
        0,    0,    0,   79,   81,   82,   79,   81,   83,   82,
      120,   82,  120,   83,   82,    0,    0,   85,   84,   83,

        0,    0,   83,   85,   84,   87,   85,   84,   86,   87,
       86,    0,    0,   88,   86,   87,    0,   86,   87,   88,
       89,   91,   88,   90,    0,   90,   89,   91,    0,   92,
       91,   90,   89,   92,   90,   89,   93,  120,   94,   92,
       93,   95,   92,    0,   96,   95,   93,   94,   96,   93,
       95,   95,   94,   96,   96,   95,   97,   98,   96,    0,
       97,   99,   98,  105,  101,  105,   97,   99,   98,   97,
       99,   98,  100,  101,  105,  105,  100,    0,  100,  101,
       94,  100,  101,   95,  102,  103,   96,  102,  130,  106,
      111,  106,  110,  102,  103,  106,  102,  115,  110,  103,

      106,  110,  130,  115,    0,  106,  115,  105,  112,  108,
      105,  108,  139,    0,  139,  108,    0,  112,  113,    0,
      108,  130,  113,  111,  114,  108,  114,  103,  113,  111,
      114,  113,  111,  114,    0,    0,  106,  107,    0,  107,
      134,  112,  122,  107,  122,  134,    0,  112,  107,  107,
      112,  134,    0,  107,  134,  119,  108,  119,  122,  139,
      149,  121,  149,  121,    0,  151,  119,  151,    0,    0,
        0,  119,  121,  121,    0,    0,    0,  123,  135,  123,
        0,  107,    0,  123,  107,  109,  135,  109,  123,  122,
        0,  109,  135,  123,    0,  135,  109,  109,  124,  119,

      124,  109,  119,    0,  125,  121,  125,  149,  121,  124,
      125,    0,  151,  131,  124,  125,    0,  138,    0,  127,
      125,  127,  131,    0,  123,  127,  138,  131,    0,  109,
      127,  138,  109,    0,    0,  127,  160,  128,    0,  128,
      136,  145,  124,  128,  136,  124,  136,    0,  128,  136,
      160,  125,  126,  128,  126,  131,    0,    0,  126,  138,
        0,  132,    0,  126,  126,  132,  127,    0,  126,  160,
      132,  132,  133,    0,  145,  132,  133,  140,    0,  140,
      145,  133,  133,  145,  128,    0,  133,    0,  140,  140,
        0,  147,    0,    0,    0,  147,  126,    0,    0,  126,

      129,  147,  129,  132,  147,    0,  129,  141,    0,  141,
        0,  129,  129,  141,  133,    0,  129,    0,  141,    0,
        0,  140,    0,  141,  140,  143,  146,  143,    0,    0,
      146,  143,  146,    0,    0,  146,  143,  150,  152,  150,
      152,  143,    0,    0,  129,    0,    0,  129,  150,  152,
      152,    0,    0,  150,  141,  142,    0,  142,    0,    0,
        0,  142,  161,  153,  161,  153,  142,  142,    0,  153,
      161,  142,  143,  161,  153,    0,  154,  162,  154,  153,
        0,  150,  152,  162,  150,  152,  162,  154,    0,    0,
        0,    0,  154,    0,    0,  155,    0,  155,  165,  142,

        0,  155,  142,  144,  165,  144,  155,  165,  165,  144,
      153,  155,    0,    0,  144,  144,    0,    0,  167,  144,
      154,    0,  157,  154,  157,  158,  167,  158,  157,    0,
      169,  158,  167,  157,  169,  167,  158,  168,  157,  168,
      169,  158,  155,  169,    0,  168,  170,  144,  168,    0,
      144,  156,  170,  156,  170,  170,    0,  156,    0,  171,
        0,    0,  156,  156,    0,  171,    0,  156,  171,  157,
        0,    0,  158,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  156,    0,    0,  156,  159,

        0,  159,    0,    0,    0,  159,    0,    0,    0,    0,
      159,  159,    0,    0,    0,  159,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  159,    0,    0,  159,  173,  173,  173,
      173,  173,  173,  174,  174,  174,  174,  174,  174,  174,
      174,  175,  175,  175,  175,  175,  175,  176,    0,    0,
        0,    0,  176,  177,    0,  177,  178,    0,  178,    0,
      178,  178,  179,  179,  179,  179,  179,  179,  180,  180,
      180,  180,  180,  180,  181,  181,    0,    0,  181,    0,

      181,  182,  182,    0,  182,  182,    0,  182,  183,  183,
      183,  183,  183,  183,  183,  184,  184,  184,  184,  184,
      184,  184,  185,  185,  185,  185,  185,  185,  185,  186,
      186,  186,  186,  186,  186,  186,  187,    0,  187,    0,
      187,  187,  188,  188,  188,  188,  188,  188,  189,  189,
      189,  189,  189,  189,  190,  190,    0,    0,  190,    0,
      190,  191,  191,    0,  191,  191,    0,  191,  192,  192,
      192,  192,  192,  192,  192,  193,  193,  193,  193,  193,
      193,  193,  194,  194,  194,  194,  194,  194,  194,  195,
      195,  195,  195,  195,  195,  195,  172,  172,  172,  172,

      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int chk_flex_debug;
int chk_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *chktext;
#line 1 "chkLex.l"
#line 2 "chkLex.l"

#include <string.h>
#include <stdio.h>
#include <stdlib.h>
//#include "y.tab.h"
//#include "chkLang.h"
#define YY_NO_UNPUT


int def_lang = 0;
int init_decl = 0;
int arguments = 0;
int in_check = 0;
int in_module = 0;
int module_decl = 0; 
int module_impl = 0;
int in_struct = 0;
int after_letter = 0;
int callmod = 0;
int clause_n = 0;
int in_spec = 0;


#line 787 "chkLex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int chklex_destroy (void );

int chkget_debug (void );

void chkset_debug (int debug_flag  );

YY_EXTRA_TYPE chkget_extra (void );

void chkset_extra (YY_EXTRA_TYPE user_defined  );

FILE *chkget_in (void );

void chkset_in  (FILE * in_str  );

FILE *chkget_out (void );

void chkset_out  (FILE * out_str  );

int chkget_leng (void );

char *chkget_text (void );

int chkget_lineno (void );

void chkset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int chkwrap (void );
#else
extern int chkwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( chktext, chkleng, 1, chkout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( chkin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( chkin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, chkin))==0 && ferror(chkin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(chkin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int chklex (void);

#define YY_DECL int chklex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after chktext and chkleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 30 "chkLex.l"


#line 972 "chkLex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! chkin )
			chkin = stdin;

		if ( ! chkout )
			chkout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			chkensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				chk_create_buffer(chkin,YY_BUF_SIZE );
		}

		chk_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of chktext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 173 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 997 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 32 "chkLex.l"
{ lineno++; ECHO;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 34 "chkLex.l"
{ ECHO; init_decl = 1; return INIT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "chkLex.l"
{ ECHO; in_module = 1; module_decl = 1; return MODULE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "chkLex.l"
{ return ALL; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 37 "chkLex.l"
{ in_spec = 1;  return SPEC; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "chkLex.l"
{ def_lang = 1; return DEFINE_LANGUAGES; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "chkLex.l"
{ def_lang = 0; return END_DEFINE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "chkLex.l"
{ in_check = 1; return CHECK; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "chkLex.l"
{ if(!arguments) ECHO;
			  					  else { chklval.string = strdup(chktext); 
									 if(debuginfo)printf("type = %s\n", chktext);
									 return TYPE;}
								}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "chkLex.l"
{ if(debuginfo) printf("GLOBAL returned\n");
		  return GLOBAL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "chkLex.l"
{ if(debuginfo) printf("NEXT returned\n");
		  return NEXT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "chkLex.l"
{ if(debuginfo) printf("UNTIL returned\n");
		  return UNTIL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "chkLex.l"
{ if(debuginfo) printf("EXIST returned\n");
		  return EXIST; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 58 "chkLex.l"
{ if(debuginfo) printf("\" returned\n"); return '"'; }	
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 60 "chkLex.l"
{in_struct = 1; ECHO;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 61 "chkLex.l"
{if(!arguments) ECHO;
								 else { chklval.string = strdup(chktext);
									if(debuginfo)printf("type = %s\n", chktext);
									return TYPE;}}
	YY_BREAK
/*[A-Za-z_][A-Za-z0-9_]*[+*]	{if(def_lang) {

				 yyless(chkleng-1); 
				 chklval.string = strdup(chktext);  
				 
				 Alpha alpha;
				 alpha = alphabet; 
				 while(alpha != NULL)
				 {
					if(!strcmp(alpha->word, chktext))
					{					
						
						return LETTER;
					}	
					alpha = alpha->next;
				 }
				 return IDENT;
				 }
				 else ECHO;}	*/
case 17:
YY_RULE_SETUP
#line 88 "chkLex.l"
{
				if(debuginfo)printf("in callident = %s\n", chktext);
				char* text = strdup(chktext);
				int l1 =  strcspn(chktext, "= ");
				yyless(l1);
				if(debuginfo)printf("chktext = %s\n", chktext);
				chklval.string = strdup(chktext);
				if(def_lang||in_spec) {//free(text);
						 return IDENT;}
				else{ 	
					char* equ = strrchr(text, '=');
					char* part2 = (char*)malloc(strlen(text) - l1 +1);
					//free(text);

					strcpy(part2, equ+1);
					equ = strrchr(part2, ' ');
					strcpy(part2, equ+1);
					if(debuginfo)printf("part2 = %s\n", part2);

					Alpha alpha;
					alpha = alphabet; 
					while(alpha != NULL)
					{
						if(!strcmp(alpha->word, part2)){
							callmod = 1;
							if(debuginfo)printf("callident %s returned\n", chklval.string);
							//free(part2);
							return CALLIDENT;}
						alpha = alpha->next;
					}
					//free(part2);
				    }
				ECHO;
			}								 				
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 122 "chkLex.l"
{	IrLang lang;
				after_letter = 0;
				
				lang = ir_lang; 
				while(lang != NULL)
				{
					if(!strcmp(lang->name, chktext))
					{
						chklval.string = strdup(chktext);
						if(debuginfo)printf("language = %s\n", chktext);
						return LANGUAGE;
					}
					lang = lang->next;
					
					
				}	
				
				if(in_spec){	chklval.string = strdup(chktext);
						if(debuginfo)printf("ident in specification = %s\n", chktext);
						return IDENT;}


				Alpha alpha;
				alpha = alphabet; 
				while(alpha != NULL)
				{
					if(!strcmp(alpha->word, chktext))
					{
						chklval.string = strdup(chktext);
						
						if(!(def_lang||init_decl)) {arguments = 1;}
						if(in_module) in_module = 0;
						
						after_letter = 1;
						if(debuginfo)printf("letter = %s\n", chktext);
						return LETTER;
					}	
					alpha = alpha->next;
				}
				
				if(in_module) { 
						in_module = 0; 
						arguments = 1; 
						chklval.string = strdup(chktext); 
						
						if(debuginfo)printf("new_letter = %s\n", chktext);
						return NEW_LETTER;}
					
				if(arguments) { 
						chklval.string = strdup(chktext); 
						if(debuginfo)printf("argument = %s\n", chktext);
						return ARGUMENT;}
									
				
				if(def_lang)  {	
						chklval.string = strdup(chktext);
						if(debuginfo)printf("ident in lang = %s\n", chktext);
						return IDENT;}
					
				if(init_decl) { 
						chklval.string = strdup(chktext);
						if(debuginfo)printf("ident in init = %s\n", chktext);
						return IDENT;}
				
				
				ECHO;
			}
	YY_BREAK
/*(([+*]*[A-Za-z_][A-Za-z0-9_]*[+*][A-Za-z0-9_]*)+)|([+*][A-Za-z_][A-Za-z0-9_]*)	{if(def_lang) {
				
				 char* string;
				 string = strdup(chktext);
				 
				 if((string[0] == '*')||(string[0] == '+'))
				 {
				 	yyless(1);
					
					return string[0];
				 }
				 char* str;
				 str = strtok(string, "+*");
				 
				 
				 yyless(strlen(str)); 
				 chklval.string = strdup(chktext);
				 			 				 
				 free(string);
				 Alpha alpha;
				 alpha = alphabet; 
				 while(alpha != NULL)
				 {
					if(!strcmp(alpha->word, chktext))
					{
						
						return LETTER;
					}	
					alpha = alpha->next;
				 }
				 return IDENT;
				 }
				 else ECHO;}*/
case 19:
YY_RULE_SETUP
#line 227 "chkLex.l"
{if(arguments||in_spec) { chklval.string = strdup(chktext); 
							 if(debuginfo)printf("operator %s returned\n", chktext);
							 return OPERATOR;}
							 else ECHO;	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 231 "chkLex.l"
{ if(arguments) { chklval.string = strdup(chktext); 
				if(debuginfo)printf("operator %s returned\n", chktext);
				return OPERATOR;}
		  if(in_spec){if(debuginfo) printf("OR returned\n");
		  		return OR;}
		  else ECHO;	 }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 237 "chkLex.l"
{ if(arguments) { chklval.string = strdup(chktext); 
				if(debuginfo)printf("operator %s returned\n", chktext);
				return OPERATOR;}
		  if(in_spec){if(debuginfo) printf("AND returned\n");
		  		return AND;}
		  else ECHO;	 }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 243 "chkLex.l"
{ if(arguments) { chklval.string = strdup(chktext); 
				if(debuginfo)printf("operator %s returned\n", chktext);
				return OPERATOR;}
		  if(in_spec){if(debuginfo) printf("NOT returned\n");
		  		return NOT;}
		  else ECHO;	  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 252 "chkLex.l"
{if(arguments){ clause_n = clause_n + 1; after_letter = 0; return '(';}
		 else if(in_check||def_lang||in_spec) return '(';
		 else ECHO;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 256 "chkLex.l"
{if(arguments){ 
			clause_n = clause_n - 1;
			if(clause_n <= 0)arguments = 0;
			return ')';}
		 else if(def_lang||in_check||in_spec) return chktext[0];
		 else ECHO;		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 263 "chkLex.l"
{if(def_lang){ callmod = 0; return chktext[0];}
		 if(arguments||in_spec){ chklval.string = strdup(chktext);
				if(debuginfo)printf("operator %s returned\n", chktext); 
				return OPERATOR;}
		 ECHO;	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 269 "chkLex.l"
{if(def_lang||callmod) { callmod = 0; return '=';}
		 if(in_spec){ chklval.string = strdup(chktext); return OPERATOR; }	
		 else ECHO;	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 273 "chkLex.l"
{ ECHO; } 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 276 "chkLex.l"
{if(arguments) {chklval.string = strdup(chktext); if(debuginfo)printf("operator = %s\n", chktext); return OPERATOR;}}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 278 "chkLex.l"
{if(module_decl) {module_decl = 0; module_impl = 1; ECHO; return '{';}
		 if(in_spec) return '{';
		 ECHO;	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 283 "chkLex.l"
{
			if(debuginfo) printf("structure or array element found = %s\n", chktext);
			if(arguments){ 
			chklval.string = strdup(chktext);
			if(debuginfo)printf("argument %s returned\n", chktext);
		 	return ARGUMENT;}
			if(in_spec){ chklval.string = strdup(chktext); return IDENT; }
		 	ECHO;}	
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 292 "chkLex.l"
{if(arguments){ 
			chklval.string = strdup(chktext);
		 	return ARGUMENT;}
		 if(in_spec){ chklval.string = strdup(chktext);
			  	return IDENT; }
		 ECHO;}	
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 299 "chkLex.l"
{ if(in_struct){in_struct = 0; ECHO;}
		  else if(module_impl) {module_impl = 0; ECHO; return '}';} 
		  if(in_spec) return '}'; } 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 303 "chkLex.l"
{if(init_decl) { init_decl = 0; ECHO; return ';';}
		 if(module_decl) { module_decl = 0; ECHO; return ';';} 	
		 if(in_check) { in_check = 0; return ';';}
		 if(def_lang) return ';';
		 if(in_spec){in_spec = 0; return ';';}
		 ECHO;	}	
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 309 "chkLex.l"
{if(after_letter){ after_letter = 0; return ':';}
		 if(in_spec){ if(debuginfo) printf(": returned in specifikation\n"); 
				chklval.string = strdup(chktext);
				return OPERATOR;}
		 ECHO;	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 318 "chkLex.l"
{ ECHO; }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 322 "chkLex.l"
{init_decl = 0; lineno++; ECHO;}		 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 325 "chkLex.l"
ECHO;
	YY_BREAK
#line 1460 "chkLex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed chkin at a new source and called
			 * chklex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = chkin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( chkwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * chktext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of chklex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					chkrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			chkrestart(chkin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) chkrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 173 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 173 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 172);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up chktext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					chkrestart(chkin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( chkwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve chktext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void chkrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        chkensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            chk_create_buffer(chkin,YY_BUF_SIZE );
	}

	chk_init_buffer(YY_CURRENT_BUFFER,input_file );
	chk_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void chk_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		chkpop_buffer_state();
	 *		chkpush_buffer_state(new_buffer);
     */
	chkensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	chk_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (chkwrap()) processing, but the only time this flag
	 * is looked at is after chkwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void chk_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	chkin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE chk_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) chkalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in chk_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) chkalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in chk_create_buffer()" );

	b->yy_is_our_buffer = 1;

	chk_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with chk_create_buffer()
 * 
 */
    void chk_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		chkfree((void *) b->yy_ch_buf  );

	chkfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a chkrestart() or at EOF.
 */
    static void chk_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	chk_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then chk_init_buffer was _probably_
     * called from chkrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void chk_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		chk_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void chkpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	chkensure_buffer_stack();

	/* This block is copied from chk_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from chk_switch_to_buffer. */
	chk_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void chkpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	chk_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		chk_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void chkensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)chkalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in chkensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)chkrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in chkensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE chk_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) chkalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in chk_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	chk_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to chklex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       chk_scan_bytes() instead.
 */
YY_BUFFER_STATE chk_scan_string (yyconst char * yystr )
{
    
	return chk_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to chklex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE chk_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) chkalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in chk_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = chk_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in chk_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up chktext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		chktext[chkleng] = (yy_hold_char); \
		(yy_c_buf_p) = chktext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		chkleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int chkget_lineno  (void)
{
        
    return chklineno;
}

/** Get the input stream.
 * 
 */
FILE *chkget_in  (void)
{
        return chkin;
}

/** Get the output stream.
 * 
 */
FILE *chkget_out  (void)
{
        return chkout;
}

/** Get the length of the current token.
 * 
 */
int chkget_leng  (void)
{
        return chkleng;
}

/** Get the current token.
 * 
 */

char *chkget_text  (void)
{
        return chktext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void chkset_lineno (int  line_number )
{
    
    chklineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see chk_switch_to_buffer
 */
void chkset_in (FILE *  in_str )
{
        chkin = in_str ;
}

void chkset_out (FILE *  out_str )
{
        chkout = out_str ;
}

int chkget_debug  (void)
{
        return chk_flex_debug;
}

void chkset_debug (int  bdebug )
{
        chk_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from chklex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    chkin = stdin;
    chkout = stdout;
#else
    chkin = (FILE *) 0;
    chkout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * chklex_init()
     */
    return 0;
}

/* chklex_destroy is for both reentrant and non-reentrant scanners. */
int chklex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		chk_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		chkpop_buffer_state();
	}

	/* Destroy the stack itself. */
	chkfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * chklex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *chkalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *chkrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void chkfree (void * ptr )
{
	free( (char *) ptr );	/* see chkrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 325 "chkLex.l"
