.de EX		
.if \\n(.$>1 .tm troff: tmac.an: \\*(.F: extra arguments ignored
.sp \\n()Pu
.ne 8v
.ie \\n(.$ .nr EX 0\\$1n
.el .nr EX 0.5i
.in +\\n(EXu
.nf
.CW
..
.de EE		
.if \\n(.$>0 .tm troff: tmac.an: \\*(.F: arguments ignored
.R
.fi
.in -\\n(EXu
.sp \\n()Pu
..
.TH flreverse 1 "Grail"
.SH NAME
flreverse \- reverse a finite language
.SH SYNOPSIS
.B flreverse fl
.sp
.B flreverse <fl
.SH DESCRIPTION
.B
flreverse
reverses the direction of all words in \fIfl\fR and
writes the result on standard output.
.B
flreverse
has no effect on empty languages and empty strings. 
.LP
\fIfl\fR must conform to the Grail format for finite languages.
.SH EXAMPLES
.EX
% cat fl
aabbcc

aaa
zzab

% flreverse fl
ccbbaa

aaa
bazz

.EE
.SH AUTHORS
Roger Robson, Darrell Raymond and Derick Wood, the Grail project
.SH "SEE ALSO"
fl(5)
