.de EX		
.if \\n(.$>1 .tm troff: tmac.an: \\*(.F: extra arguments ignored
.sp \\n()Pu
.ne 8v
.ie \\n(.$ .nr EX 0\\$1n
.el .nr EX 0.5i
.in +\\n(EXu
.nf
.CW
..
.de EE		
.if \\n(.$>0 .tm troff: tmac.an: \\*(.F: arguments ignored
.R
.fi
.in -\\n(EXu
.sp \\n()Pu
..
.TH fmenum 1 "Grail"
.SH NAME
fmenum \- enumerate the language of a machine
.SH SYNOPSIS
.B fmenum [-n num] fa
.sp
.B fmenum [-n num] <fm
.SH DESCRIPTION
.B
fmenum 
enumerates the language of \fIfm\fR and writes the strings on its 
standard output.  It produces 100 strings (or \fInum\fR strings, 
if \fI-c num\fR is specified) that belong to the language of \fIfm\fR.  
.B
fmenum
can enumerate the language of both deterministic and
nondeterministic machines.
.B
fmenum 
produces strings in order of their length, shortest first;
within the same length, they are lexicographically ordered.
.LP
\fIfm\fR must conform to the Grail format for machines.
.SH EXAMPLES
.EX
% cat nfm1
(START) |- 1
1 a 2
1 a 3
2 b 2
3 b 3
2 c 4
3 c 5
4 d 4
5 d 5
4 -| (FINAL)
5 -| (FINAL)

% fmenum -n 10 nfm1
ac
abc
acd
abbc
abcd
acdd
abbbc
abbcd
abcdd
acddd

% fmenum -n 5 <nfm1
ac
abc
acd
abbc
abcd

.EE
.SH AUTHORS
Darrell Raymond and Derick Wood, the Grail project
.SH "SEE ALSO"
fm(5), fmexec(1)
