.de EX		
.if \\n(.$>1 .tm troff: tmac.an: \\*(.F: extra arguments ignored
.sp \\n()Pu
.ne 8v
.ie \\n(.$ .nr EX 0\\$1n
.el .nr EX 0.5i
.in +\\n(EXu
.nf
.CW
..
.de EE		
.if \\n(.$>0 .tm troff: tmac.an: \\*(.F: arguments ignored
.R
.fi
.in -\\n(EXu
.sp \\n()Pu
..
.TH fmreach 1 "Grail"
.SH NAME
fmreach \- compute the reachable subset of a machine
.SH SYNOPSIS
.B fmreach fm
.sp
.B fmreach <fm
.SH DESCRIPTION
.B
fmreach
finds all reachable states of \fIfm\fR and writes on its
standard output only instructions involving those states.
.LP
\fIfm\fR must conform to the Grail format for machines.
.SH EXAMPLES
.EX
% cat dfm4
(START) |- 0
0 a 1
0 g 0
0 b 4
1 c 2
2 d 3
3 -| (FINAL)
4 e 5
5 f 6
6 -| (FINAL)

% fmreach <dfm4
(START) |- 0
0 a 1
0 b 4
0 g 0
1 c 2
2 d 3
4 e 5
5 f 6
3 -| (FINAL)
6 -| (FINAL)

% cat dfm6
(START) |- 3
3 a 4
4 b 5
5 -| (FINAL)
1 a 2
2 b 6
6 -| (FINAL)

% fmreach dfm6
(START) |- 3
3 a 4 
4 b 5 
5 -| (FINAL)

.EE
.SH AUTHORS
Darrell Raymond and Derick Wood, the Grail project
.SH "SEE ALSO"
fm(5)
