.de EX		
.if \\n(.$>1 .tm troff: tmac.an: \\*(.F: extra arguments ignored
.sp \\n()Pu
.ne 8v
.ie \\n(.$ .nr EX 0\\$1n
.el .nr EX 0.5i
.in +\\n(EXu
.nf
.CW
..
.de EE		
.if \\n(.$>0 .tm troff: tmac.an: \\*(.F: arguments ignored
.R
.fi
.in -\\n(EXu
.sp \\n()Pu
..
.TH fmstats 1 "Grail"
.SH NAME
fmstats \- output some statistics about a machine
.SH SYNOPSIS
.B fmstats fm
.sp
.B fmstats <fm
.SH DESCRIPTION
.B
fmstats
produces the following statistics about a machine: 
.LP
1. number of states
2. number of start states
3. number of final states
4. number of reachable states
5. number of instructions
.B
fmstats
does not count pseudo-instructions or pseudo-states.
.LP
\fIfm\fR must conform to the Grail format for machines.
.LP
.SH EXAMPLES
.EX
% cat dfm5
(START) |- 0
0 a 1
1 c 2
2 e 3
3 -| (FINAL)
1 b 0
2 d 0

% fmstats dfm5
1 1 4 4 5
.EE
.SH AUTHORS
Darrell Raymond and Derick Wood, the Grail project
.SH "SEE ALSO"
fm(5)
