.de EX		
.if \\n(.$>1 .tm troff: tmac.an: \\*(.F: extra arguments ignored
.sp \\n()Pu
.ne 8v
.ie \\n(.$ .nr EX 0\\$1n
.el .nr EX 0.5i
.in +\\n(EXu
.nf
.CW
..
.de EE		
.if \\n(.$>0 .tm troff: tmac.an: \\*(.F: arguments ignored
.R
.fi
.in -\\n(EXu
.sp \\n()Pu
..
.TH isnull 1 "Grail"
.SH NAME
isnull \- test re for equivalence to empty string
.SH SYNOPSIS
.B isnull re
.sp
.B isnull <re
.SH DESCRIPTION
.B
isnull
tests \fIre\fR to see if it is the empty string.
.B
isnull
returns 1 and writes \fBis empty string\fR on standard Output
if \fIre\fR is the empty string; it returns 0 and writes
\fBis not empty string\fR otherwise.
.LP
\fIre\fR must conform to the Grail format for regular expressions.
.SH EXAMPLES
.EX
% cat re1
{}

% isnull re1
is not empty string

% cat re2
""
% isnull re2
is empty string

% cat re3
(a+b)*(abc)

% isnull re3
is not empty string

.EE
.SH AUTHORS
Darrell Raymond and Derick Wood, the Grail project
.SH "SEE ALSO"
re(5), isempty(1)
