.de EX		
.if \\n(.$>1 .tm troff: tmac.an: \\*(.F: extra arguments ignored
.sp \\n()Pu
.ne 8v
.ie \\n(.$ .nr EX 0\\$1n
.el .nr EX 0.5i
.in +\\n(EXu
.nf
.CW
..
.de EE		
.if \\n(.$>0 .tm troff: tmac.an: \\*(.F: arguments ignored
.R
.fi
.in -\\n(EXu
.sp \\n()Pu
..
.TH isuniv 1 "Grail"
.SH NAME
isuniv \- test machine for universality
.SH SYNOPSIS
.B isuniv fa
.sp
.B isuniv <fa
.SH DESCRIPTION
.B
isuniv
tests if \fIfa\fR is universal\(emthat is, complete and 
all reachable states are also final states.
.B
isuniv
returns 1 and writes \fBuniversal\fR on standard output
if the input fa is universal; it returns 0 and writes
\fBnonuniversal\fR otherwise.
.LP
\fIfa\fR must conform to the Grail format for machines.
.SH EXAMPLES
.EX
% cat dfm6
(START) |- 0
0 a 1
0 b 2
0 -| (FINAL)
1 b 2
1 a 0
2 a 1
2 b 2
1 -| (FINAL)
2 -| (FINAL)

% isuniv dfm6
universal

% cat dfm1
(START) |- 0
0 a 1
1 b 2
2 -| (FINAL)

% isuniv dfm1
nonuniversal

.EE
.SH AUTHORS
Darrell Raymond and Derick Wood, the Grail project
.SH "SEE ALSO"
fm(5), fmcomp(1)
