
#line 3 "input.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;

int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + (yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[(yy_more_offset)], (yytext_ptr), yyleng + 1 ); \
	yyleng += (yy_more_offset); \
	(yy_prev_more_offset) = (yy_more_offset); \
	(yy_more_offset) = 0; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 135
#define YY_END_OF_BUFFER 136
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[595] =
    {   0,
      136,  134,  135,    1,  134,  135,    1,  135,  119,  134,
      135,  134,  135,  116,  134,  135,   80,  134,  135,   81,
      134,  135,   93,  134,  135,   91,  134,  135,  120,  134,
      135,   92,  134,  135,  112,  134,  135,   94,  134,  135,
      131,  134,  135,  131,  134,  135,  121,  134,  135,  122,
      134,  135,  104,  134,  135,  100,  134,  135,  105,  134,
      135,   68,  132,  134,  135,  132,  134,  135,  132,  134,
      135,  132,  134,  135,   60,  132,  134,  135,   61,  132,
      134,  135,   63,  132,  134,  135,   64,  132,  134,  135,
      132,  134,  135,  132,  134,  135,  132,  134,  135,  132,

      134,  135,  132,  134,  135,   62,  132,  134,  135,  132,
      134,  135,  132,  134,  135,   70,  132,  134,  135,   72,
      132,  134,  135,   69,  132,  134,  135,   71,  132,  134,
      135,  132,  134,  135,   65,  132,  134,  135,   66,  132,
      134,  135,   67,  132,  134,  135,   82,  134,  135,   83,
      134,  135,  132,  134,  135,  132,  134,  135,  132,  134,
      135,  132,  134,  135,  132,  134,  135,  132,  134,  135,
      132,  134,  135,  132,  134,  135,  132,  134,  135,  132,
      134,  135,  132,  134,  135,  132,  134,  135,  132,  134,
      135,  132,  134,  135,  132,  134,  135,   84,  134,  135,

      115,  134,  135,   85,  134,  135,  134,  135,  101,  133,
        2,  113,  111,  131,  123,   90,   96,  102,  103,   97,
      132,  132,   57,  132,   59,  132,  132,  132,   55,  132,
       73,  132,  132,  132,  132,  132,   56,  132,   58,  132,
       54,  132,  132,  132,  132,  132,   25,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  110,  132,  132,  132,   42,  132,  132,  132,  132,
      132,  132,  132,  132,    4,  130,  129,  114,   98,   99,
       75,  132,   77,  132,  132,  132,  132,  132,  132,  132,

      132,   74,  132,   76,  132,  132,  132,  132,  132,  132,
      132,  132,   29,  132,  132,  132,  132,  132,   79,  132,
       78,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,    8,  132,  132,  132,  132,  132,  132,
      132,  132,  132,   95,  132,  132,  132,  132,  132,  132,
      132,  132,  117,  132,  127,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,   32,  132,  132,   31,  132,
       10,  132,  132,    9,  132,  132,  132,  132,  132,  132,
      132,  132,  124,  132,  132,  132,   52,  132,   47,  132,
      132,   13,  132,  132,   87,  132,  132,   50,  132,  132,

       51,  132,   88,  132,   89,  132,  107,  132,  132,  106,
      132,  132,   46,  132,  108,  132,  132,   49,  132,  118,
      132,    3,    4,  127,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  128,  132,   86,  132,  132,   12,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,   11,  132,   53,  132,   41,  132,  132,  132,
      132,  109,  132,   48,  132,   30,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,   22,  132,    7,  132,
      132,  132,  132,  132,  132,  132,   23,  132,  126,  132,
        5,  132,  132,  132,  132,  132,  132,  132,  132,  132,

      132,  132,  132,  132,  132,   17,  132,   24,  132,  132,
      132,   14,  132,  132,  132,  132,   45,  132,   27,  132,
       15,  132,  132,  132,   16,  132,  132,  132,   21,  132,
       43,  132,   44,  132,    6,  132,  132,  132,  132,  132,
      132,  132,   26,  132,  132,  132,   33,  132,   34,  132,
      132,  132,  132,  132,  132,   39,  132,  132,   20,  132,
      132,  132,   18,  132,  132,  132,  132,  132,  132,   28,
      132,   19,  132,  132,  125,  132,  132,  132,  132,   36,
      132,  132,  132,   35,  132,  132,  132,  132,   38,  132,
       40,  132,   37,  132

    } ;

static yyconst flex_int16_t yy_accept[396] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       20,   23,   26,   29,   32,   35,   38,   41,   44,   47,
       50,   53,   56,   59,   62,   66,   69,   72,   75,   79,
       83,   87,   91,   94,   97,  100,  103,  106,  110,  113,
      116,  120,  124,  128,  132,  135,  139,  143,  147,  150,
      153,  156,  159,  162,  165,  168,  171,  174,  177,  180,
      183,  186,  189,  192,  195,  198,  201,  204,  207,  209,
      210,  210,  211,  212,  213,  214,  214,  215,  215,  215,
      216,  217,  217,  218,  219,  220,  221,  222,  223,  225,
      227,  228,  229,  231,  233,  234,  235,  236,  237,  239,

      241,  243,  243,  244,  245,  246,  247,  249,  250,  251,
      252,  253,  254,  255,  256,  257,  258,  259,  260,  261,
      262,  263,  264,  265,  266,  267,  268,  269,  270,  271,
      272,  274,  275,  276,  278,  279,  280,  281,  282,  283,
      284,  285,  285,  286,  286,  287,  287,  287,  287,  288,
      289,  290,  291,  293,  295,  296,  297,  298,  299,  300,
      301,  302,  304,  306,  306,  307,  308,  309,  310,  311,
      312,  313,  315,  316,  317,  318,  319,  321,  323,  324,
      325,  326,  327,  328,  329,  330,  331,  332,  333,  334,
      336,  337,  338,  339,  340,  341,  342,  343,  344,  346,

      347,  348,  349,  350,  351,  352,  353,  355,  355,  356,
      357,  358,  359,  360,  361,  362,  363,  364,  364,  365,
      366,  368,  369,  371,  373,  374,  376,  377,  378,  379,
      380,  381,  382,  383,  385,  386,  387,  389,  391,  392,
      394,  395,  397,  398,  400,  401,  403,  405,  407,  409,
      410,  412,  413,  415,  417,  418,  420,  422,  422,  424,
      424,  425,  426,  427,  428,  429,  430,  431,  432,  433,
      434,  435,  436,  437,  439,  440,  442,  443,  444,  445,
      446,  447,  448,  449,  450,  451,  452,  453,  455,  457,
      459,  460,  461,  462,  464,  466,  468,  469,  470,  471,

      472,  473,  474,  475,  476,  477,  479,  481,  482,  483,
      484,  485,  486,  487,  489,  491,  493,  494,  495,  496,
      497,  498,  499,  500,  501,  502,  503,  504,  505,  506,
      508,  510,  511,  512,  514,  515,  516,  517,  519,  521,
      523,  524,  525,  527,  528,  529,  531,  533,  535,  537,
      538,  539,  540,  541,  542,  543,  545,  546,  547,  549,
      551,  552,  553,  554,  555,  556,  558,  559,  561,  562,
      563,  565,  566,  567,  568,  569,  570,  572,  574,  575,
      577,  578,  579,  580,  582,  583,  584,  586,  587,  588,
      589,  591,  593,  595,  595

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    1,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   22,   22,   22,   22,   22,   22,   23,   24,   25,
       26,   27,    1,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,    1,   55,    1,   56,    1,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   44,   44,   66,   67,   68,
       69,   70,   44,   71,   72,   73,   74,   44,   75,   76,
       77,   44,   78,   79,   80,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[81] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    1,    3,    3,
        3,    3,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    1,    1,    4,    3,    3,    3,    3,
        3,    3,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[401] =
    {   0,
        0,  495,  501,  503,  503,  503,  474,  493,  503,  503,
      503,  503,  503,  503,   65,  481,  503,   76,   67,   59,
      503,   75,  503,   76,   80,  449,   68,  464,   87,   84,
       91,    0,   76,  447,    0,  447,   99,    0,  103,   92,
       47,  448,    0,  464,   61,    0,    0,    0,  503,  503,
      420,  421,  432,  416,  477,  418,  416,  423,  421,  411,
      420,  419,  411,  409,   78,  503,  503,  503,  147,  503,
      471,  503,  503,  503,  503,  135,  141,  145,  155,  503,
      503,  449,  450,  503,  503,  447,    0,  145,    0,    0,
      427,  430,    0,  441,  140,  431,  436,  149,    0,    0,

        0,  165,  152,  428,  426,  419,  103,  437,  436,  390,
      416,  422,  409,  127,  428,  430,  425,  417,  427,  397,
      413,  420,  142,  406,  414,  378,  377,  378,  374,  388,
      124,  384,  367,    0,  373,  384,  374,  374,  367,  368,
      365,  432,  503,  189,  174,  193,    0,  197,  201,  503,
      503,  503,    0,    0,  398,  397,  397,  388,  384,  153,
      393,    0,    0,  206,  383,  381,  394,  380,  382,  376,
      394,    0,  376,  359,  372,  154,    0,    0,  373,  369,
      364,  384,  368,  199,  347,  369,  381,  369,  377,    0,
      361,  347,  349,  339,  343,  344,  329,  340,    0,  327,

      340,  332,  335,  327,  335,  323,    0,  231,    0,  359,
      361,  355,  208,  343,  346,  355,  346,  218,  345,  353,
        0,  352,    0,    0,  338,    0,  319,  345,  337,  346,
      336,  338,  344,  339,  331,  338,    0,    0,  322,    0,
      325,    0,  338,    0,  292,  307,    0,    0,    0,  304,
        0,  305,    0,    0,  297,  344,    0,  360,  503,  240,
        0,  321,  112,  327,  314,  312,  325,  203,  325,  323,
      323,  225,  322,    0,  325,  306,  290,  320,  317,  315,
      302,  314,  300,  314,  311,  210,  309,    0,    0,    0,
      284,  279,  267,    0,    0,    0,  306,  309,  308,  289,

      302,  300,  291,  303,  300,    0,    0,  283,  298,  284,
      255,  293,  294,    0,    0,    0,  267,  294,  291,  288,
      291,  285,  249,  245,  243,  286,  268,  272,  275,    0,
        0,  263,  273,    0,  262,  260,  274,    0,    0,    0,
      212,  258,    0,  276,  258,    0,    0,    0,    0,  271,
      267,  268,  257,  252,  256,    0,  260,  265,    0,    0,
      262,  262,  258,  252,  258,    0,  248,    0,  241,  238,
        0,  240,  246,  252,  241,  235,    0,    0,  245,    0,
      238,  208,  224,    0,  195,  177,    0,  167,  146,   94,
        0,    0,    0,  503,  262,  265,  269,  101,  273,  275

    } ;

static yyconst flex_int16_t yy_def[401] =
    {   0,
      394,    1,  394,  394,  394,  394,  394,  395,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  394,  394,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  394,  394,  394,  397,  394,
      395,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,

      396,  394,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  397,  394,  397,  394,  394,  398,  394,  394,  394,
      394,  394,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  394,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  396,  396,  399,  400,  396,
      396,  396,  396,  396,  396,  396,  396,  394,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  399,  394,  399,
      400,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  394,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,    0,  394,  394,  394,  394,  394,  394

    } ;

static yyconst flex_int16_t yy_nxt[584] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    4,    9,    4,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       35,   38,   39,   35,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   35,   51,   52,   53,   35,
       54,   55,   35,   35,   56,   35,   57,   58,   59,   60,
       61,   62,   35,   63,   64,   65,   35,   66,   67,   68,
       73,   80,  121,   76,   81,   77,   77,   77,   77,  122,
       82,   74,   76,  102,   77,   77,   77,   77,   79,   83,

       84,   85,   86,  209,   78,  125,   78,   79,   88,   95,
       78,  103,   89,   90,   96,   98,  107,   78,  104,   99,
      100,  108,  105,  119,  109,   91,  113,   79,   92,  126,
       93,  393,  106,   78,  114,   78,   79,  101,  170,   78,
      115,  116,  297,  110,   78,  140,  141,  117,  118,  143,
      144,  171,  120,  145,  145,  145,  145,   76,  298,   77,
       77,   77,   77,  146,  146,  146,  146,  178,  148,  188,
      148,  179,   79,  149,  149,  149,  149,  153,  154,  158,
      159,  162,  163,  164,  164,  164,  164,  165,  197,  189,
      166,  143,  145,  145,  145,  145,  198,  392,  215,  229,

      147,   79,  216,  230,  391,   79,  390,  208,  208,  208,
      208,  146,  146,  146,  146,  149,  149,  149,  149,  149,
      149,  149,  149,  218,  164,  164,  164,  164,  236,  237,
      303,  359,  360,  259,   79,  265,  272,  272,  272,  272,
      320,  389,  259,  272,  272,  272,  272,  304,  147,  260,
      260,  260,  260,  388,  387,  266,  321,  267,  260,  260,
      260,  260,   71,   71,   71,   71,   87,   87,   87,  142,
      142,  142,  142,  258,  258,  258,  258,  261,  261,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,

      365,  364,  363,  362,  361,  358,  357,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  302,  301,  300,
      299,  296,  259,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  271,  270,  269,  268,
      264,  263,  262,  257,  256,  255,  254,  253,  252,  251,

      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  235,  234,  233,  232,  231,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  217,  214,
      213,  212,  211,  210,  143,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  196,  195,  194,  193,  192,  191,
      190,  187,  186,  185,  184,  183,  182,  181,  180,  177,
      176,  175,  174,  173,  172,  169,  168,  167,  161,  160,
      157,  156,  155,  152,  151,  150,   72,  139,  138,  137,
      136,  135,  134,  133,  132,  131,  102,  130,  129,  128,
      127,  124,  123,  112,  111,   97,   94,   75,   72,   70,

      394,   69,    3,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394
    } ;

static yyconst flex_int16_t yy_chk[584] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       15,   20,   41,   19,   20,   19,   19,   19,   19,   41,
       22,   15,   18,   30,   18,   18,   18,   18,   19,   22,

       22,   24,   24,  398,   18,   45,   18,   18,   25,   27,
       18,   30,   25,   25,   27,   29,   33,   18,   31,   29,
       29,   33,   31,   40,   33,   25,   37,   19,   25,   45,
       25,  390,   31,   18,   37,   18,   18,   29,  107,   18,
       37,   39,  263,   33,   18,   65,   65,   39,   39,   69,
       69,  107,   40,   76,   76,   76,   76,   77,  263,   77,
       77,   77,   77,   78,   78,   78,   78,  114,   79,  123,
       79,  114,   77,   79,   79,   79,   79,   88,   88,   95,
       95,   98,   98,  102,  102,  102,  102,  103,  131,  123,
      103,  144,  145,  145,  145,  145,  131,  389,  160,  176,

       78,   77,  160,  176,  388,  145,  386,  144,  144,  144,
      144,  146,  146,  146,  146,  148,  148,  148,  148,  149,
      149,  149,  149,  164,  164,  164,  164,  164,  184,  184,
      268,  341,  341,  208,  145,  213,  218,  218,  218,  218,
      286,  385,  260,  272,  272,  272,  272,  268,  146,  208,
      208,  208,  208,  383,  382,  213,  286,  213,  260,  260,
      260,  260,  395,  395,  395,  395,  396,  396,  396,  397,
      397,  397,  397,  399,  399,  399,  399,  400,  400,  381,
      379,  376,  375,  374,  373,  372,  370,  369,  367,  365,
      364,  363,  362,  361,  358,  357,  355,  354,  353,  352,

      351,  350,  345,  344,  342,  337,  336,  335,  333,  332,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  313,  312,  311,  310,  309,  308,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  293,  292,
      291,  287,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  273,  271,  270,  269,  267,  266,  265,
      264,  262,  258,  256,  255,  252,  250,  246,  245,  243,
      241,  239,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  225,  222,  220,  219,  217,  216,  215,  214,
      212,  211,  210,  206,  205,  204,  203,  202,  201,  200,

      198,  197,  196,  195,  194,  193,  192,  191,  189,  188,
      187,  186,  185,  183,  182,  181,  180,  179,  175,  174,
      173,  171,  170,  169,  168,  167,  166,  165,  161,  159,
      158,  157,  156,  155,  142,  141,  140,  139,  138,  137,
      136,  135,  133,  132,  130,  129,  128,  127,  126,  125,
      124,  122,  121,  120,  119,  118,  117,  116,  115,  113,
      112,  111,  110,  109,  108,  106,  105,  104,   97,   96,
       94,   92,   91,   86,   83,   82,   71,   64,   63,   62,
       61,   60,   59,   58,   57,   56,   55,   54,   53,   52,
       51,   44,   42,   36,   34,   28,   26,   16,    8,    7,

        3,    2,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[136] =
    {   0,
1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() ((yy_more_offset) = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(yy_more_offset) = (yy_prev_more_offset); \
	yyleng -= (yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "input.l"
/***************************************************************  -*-C-*-  ***/
#line 3 "input.l"
/**CFile***********************************************************************

  FileName    [input.l]

  PackageName [parser]

  Synopsis    [Lexical analyzer for the NuSMV input language]

  SeeAlso     [grammar.y]

  Author      [Marco Roveri]

  Copyright   [
  This file is part of the ``parser'' package of NuSMV version 2. 
  Copyright (C) 1998-2005 by CMU and ITC-irst. 

  NuSMV version 2 is free software; you can redistribute it and/or 
  modify it under the terms of the GNU Lesser General Public 
  License as published by the Free Software Foundation; either 
  version 2 of the License, or (at your option) any later version.

  NuSMV version 2 is distributed in the hope that it will be useful, 
  but WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public 
  License along with this library; if not, write to the Free Software 
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA.

  For more information on NuSMV see <http://nusmv.irst.itc.it>
  or email to <nusmv-users@irst.itc.it>.
  Please report bugs to <nusmv-users@irst.itc.it>.

  To contact the NuSMV development board, email to <nusmv@irst.itc.it>. ]

******************************************************************************/
 
#include "util.h"

#include "utils/utils.h"
#include "utils/ustring.h"
#include "node/node.h"
#include "utils/error.h"
#include "utils/WordNumber.h"

#include <ctype.h>
#include <stdlib.h> /* for strtol */
#include <limits.h> /* for LLONG_MAX */
#include <errno.h>

#include "grammar.h" /* For yacc/lex interaction */

/* For direct interpretation of atomic (ATOM and NUMBER)
   and boolan (TRUE and FALSE) constants. */
#include "symbols.h" 

static char rcsid[] UTIL_UNUSED = "$Id: input.l,v 1.12.2.4.4.30.4.6 2007/05/11 08:37:48 nusmv Exp $";

static int nusmv_skip_comment ARGS((void));

EXTERN boolean parser_parse_real  ARGS((void));
EXTERN void Parser_switch_to_psl ARGS((void));

/* 
   The following are needed in order to allow parsing of long
   comments, that otherwise will cause errors since flex thinks that
   it is using REJECT even if it isn't.  The "%option noreject" seems
   to be ignored in the latest (and previous) versions of flex.
*/
#ifdef YY_USES_REJECT
#undef YY_USES_REJECT
#endif


#define YY_INPUT(buf, result, max_size) \
	if ( YY_CURRENT_BUFFER->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for (n=0; n<max_size && \
		     (c = getc(yyin)) != EOF && \
                     c!=' ' && c!='\n' && c!='\t' && c!='\r' && c!='\f'; ++n ) \
			buf[n] = (char) c; \
		if (c==' ' || c=='\n' || c=='\t' || c=='\r' || c=='\f') buf[n++] = (char) c; \
		if (c == EOF && ferror(yyin)) YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if(errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}


#line 932 "input.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 112 "input.l"

#line 1119 "input.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 395 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 503 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_prev_more_offset); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 113 "input.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 114 "input.l"
nusmv_skip_comment();
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 115 "input.l"
sscanf(yytext,"# %d",&yylineno);
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 116 "input.l"
rpterr("Unexpected preprocessor directive:\n %s\n",yytext);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 117 "input.l"
{yylval.lineno = yylineno; return(TOK_MODULE);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 118 "input.l"
{yylval.lineno = yylineno; return(TOK_PROCESS);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 119 "input.l"
{yylval.lineno = yylineno; return(TOK_DEFINE);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 120 "input.l"
{yylval.lineno = yylineno; return(TOK_VAR);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 121 "input.l"
{yylval.lineno = yylineno; return(TOK_IVAR);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 122 "input.l"
{yylval.lineno = yylineno; return(TOK_INIT);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 123 "input.l"
{yylval.lineno = yylineno; return(TOK_TRANS);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 124 "input.l"
{yylval.lineno = yylineno; return(TOK_INVAR);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 125 "input.l"
{yylval.lineno = yylineno; return(TOK_SPEC);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 126 "input.l"
{yylval.lineno = yylineno; return(TOK_CTLSPEC);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 127 "input.l"
{yylval.lineno = yylineno; return(TOK_LTLSPEC);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 128 "input.l"
{yylval.lineno = yylineno; Parser_switch_to_psl(); return(TOK_PSLSPEC);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 129 "input.l"
{yylval.lineno = yylineno; return(TOK_COMPUTE);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 130 "input.l"
{yylval.lineno = yylineno; return(TOK_INVARSPEC);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 131 "input.l"
{yylval.lineno = yylineno; return(TOK_CONSTRAINT);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 132 "input.l"
{yylval.lineno = yylineno; return(TOK_CONSTANTS);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 133 "input.l"
{yylval.lineno = yylineno; return(TOK_SIMPWFF);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 134 "input.l"
{yylval.lineno = yylineno; return(TOK_CTLWFF);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 135 "input.l"
{yylval.lineno = yylineno; return(TOK_LTLWFF);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 136 "input.l"
{yylval.lineno = yylineno; return(TOK_COMPWFF);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 137 "input.l"
{yylval.lineno = yylineno; return(TOK_INCONTEXT);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 138 "input.l"
{yylval.lineno = yylineno; return(TOK_FAIRNESS);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 139 "input.l"
{yylval.lineno = yylineno; return(TOK_JUSTICE);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 140 "input.l"
{yylval.lineno = yylineno; return(TOK_COMPASSION);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 141 "input.l"
{yylval.lineno = yylineno; return(TOK_ISA);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 142 "input.l"
{yylval.lineno = yylineno; return(TOK_ASSIGN);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 143 "input.l"
{yylval.lineno = yylineno; return(TOK_GOTO);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 145 "input.l"
{yylval.lineno = yylineno; return(TOK_GAME);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 146 "input.l"
{yylval.lineno = yylineno; return(TOK_PLAYER_1);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 147 "input.l"
{yylval.lineno = yylineno; return(TOK_PLAYER_2);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 148 "input.l"
{yylval.lineno = yylineno; return(TOK_REACHTARGET);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 149 "input.l"
{yylval.lineno = yylineno; return(TOK_AVOIDTARGET);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 150 "input.l"
{yylval.lineno = yylineno; return(TOK_REACHDEADLOCK);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 151 "input.l"
{yylval.lineno = yylineno; return(TOK_AVOIDDEADLOCK);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 152 "input.l"
{yylval.lineno = yylineno; return(TOK_BUCHIGAME);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 153 "input.l"
{yylval.lineno = yylineno; return(TOK_GENREACTIVITY);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 155 "input.l"
{yylval.lineno = yylineno; return(TOK_ARRAY);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 156 "input.l"
{yylval.lineno = yylineno; return(TOK_OF);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 157 "input.l"
{yylval.lineno = yylineno; return(TOK_BOOLEAN);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 158 "input.l"
{yylval.lineno = yylineno; return(TOK_INTEGER);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 159 "input.l"
{yylval.lineno = yylineno; return(TOK_INTEGER);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 160 "input.l"
{yylval.lineno = yylineno; return(TOK_REAL);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 161 "input.l"
{yylval.lineno = yylineno; return(TOK_REAL);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 162 "input.l"
{yylval.lineno = yylineno; return(TOK_WORD1);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 163 "input.l"
{yylval.lineno = yylineno; return(TOK_WORD);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 164 "input.l"
{yylval.lineno = yylineno; return(TOK_WORD);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 165 "input.l"
{yylval.lineno = yylineno; return(TOK_BOOL);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 167 "input.l"
{yylval.lineno = yylineno; return(TOK_WAREAD);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 168 "input.l"
{yylval.lineno = yylineno; return(TOK_WAWRITE);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 170 "input.l"
{yylval.lineno = yylineno; return(TOK_EX);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 171 "input.l"
{yylval.lineno = yylineno; return(TOK_AX);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 172 "input.l"
{yylval.lineno = yylineno; return(TOK_EF);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 173 "input.l"
{yylval.lineno = yylineno; return(TOK_AF);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 174 "input.l"
{yylval.lineno = yylineno; return(TOK_EG);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 175 "input.l"
{yylval.lineno = yylineno; return(TOK_AG);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 176 "input.l"
{yylval.lineno = yylineno; return(TOK_EE);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 177 "input.l"
{yylval.lineno = yylineno; return(TOK_OP_FUTURE);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 178 "input.l"
{yylval.lineno = yylineno; return(TOK_OP_ONCE);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 179 "input.l"
{yylval.lineno = yylineno; return(TOK_OP_GLOBAL);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 180 "input.l"
{yylval.lineno = yylineno; return(TOK_OP_HISTORICAL);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 181 "input.l"
{yylval.lineno = yylineno; return(TOK_OP_NEXT);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 182 "input.l"
{yylval.lineno = yylineno; return(TOK_OP_PREC);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 183 "input.l"
{yylval.lineno = yylineno; return(TOK_OP_NOTPRECNOT);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 184 "input.l"
{yylval.lineno = yylineno; return(TOK_AA);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 185 "input.l"
{yylval.lineno = yylineno; return(TOK_UNTIL);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 186 "input.l"
{yylval.lineno = yylineno; return(TOK_SINCE);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 187 "input.l"
{yylval.lineno = yylineno; return(TOK_RELEASES);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 188 "input.l"
{yylval.lineno = yylineno; return(TOK_TRIGGERED);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 189 "input.l"
{yylval.lineno = yylineno; return(TOK_BUNTIL);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 190 "input.l"
{yylval.lineno = yylineno; return(TOK_EBF);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 191 "input.l"
{yylval.lineno = yylineno; return(TOK_ABF);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 192 "input.l"
{yylval.lineno = yylineno; return(TOK_EBG);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 193 "input.l"
{yylval.lineno = yylineno; return(TOK_ABG);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 194 "input.l"
{yylval.lineno = yylineno; return(TOK_MMIN);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 195 "input.l"
{yylval.lineno = yylineno; return(TOK_MMAX);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 196 "input.l"
{yylval.lineno = yylineno; return(TOK_LP);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 197 "input.l"
{yylval.lineno = yylineno; return(TOK_RP);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 198 "input.l"
{yylval.lineno = yylineno; return(TOK_LB);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 199 "input.l"
{yylval.lineno = yylineno; return(TOK_RB);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 200 "input.l"
{yylval.lineno = yylineno; return(TOK_LCB);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 201 "input.l"
{yylval.lineno = yylineno; return(TOK_RCB);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 202 "input.l"
{
				yylval.node = new_node(FALSEEXP,Nil,Nil);
				return(TOK_FALSEEXP);
			}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 206 "input.l"
{
				yylval.node = new_node(TRUEEXP,Nil,Nil);
				return(TOK_TRUEEXP);
			}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 210 "input.l"
{yylval.lineno = yylineno; return(TOK_CASE);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 211 "input.l"
{yylval.lineno = yylineno; return(TOK_ESAC);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 212 "input.l"
{yylval.lineno = yylineno; return(TOK_EQDEF);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 213 "input.l"
{yylval.lineno = yylineno; return(TOK_PLUS);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 214 "input.l"
{yylval.lineno = yylineno; return(TOK_MINUS);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 215 "input.l"
{yylval.lineno = yylineno; return(TOK_TIMES);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 216 "input.l"
{yylval.lineno = yylineno; return(TOK_DIVIDE);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 217 "input.l"
{yylval.lineno = yylineno; return(TOK_MOD);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 218 "input.l"
{yylval.lineno = yylineno; return(TOK_LSHIFT);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 219 "input.l"
{yylval.lineno = yylineno; return(TOK_RSHIFT);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 220 "input.l"
{yylval.lineno = yylineno; return(TOK_LROTATE);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 221 "input.l"
{yylval.lineno = yylineno; return(TOK_RROTATE);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 222 "input.l"
{yylval.lineno = yylineno; return(TOK_EQUAL);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 223 "input.l"
{yylval.lineno = yylineno; return(TOK_NOTEQUAL);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 224 "input.l"
{yylval.lineno = yylineno; return(TOK_LE);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 225 "input.l"
{yylval.lineno = yylineno; return(TOK_GE);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 226 "input.l"
{yylval.lineno = yylineno; return(TOK_LT);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 227 "input.l"
{yylval.lineno = yylineno; return(TOK_GT);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 228 "input.l"
{yylval.lineno = yylineno; return(TOK_NEXT);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 229 "input.l"
{yylval.lineno = yylineno; return(TOK_SMALLINIT);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 230 "input.l"
{yylval.lineno = yylineno; return(TOK_SELF);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 231 "input.l"
{yylval.lineno = yylineno; return(TOK_UNION);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 232 "input.l"
{yylval.lineno = yylineno; return(TOK_SETIN);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 233 "input.l"
{yylval.lineno = yylineno; return(TOK_TWODOTS);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 234 "input.l"
{yylval.lineno = yylineno; return(TOK_DOT);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 235 "input.l"
{yylval.lineno = yylineno; return(TOK_IMPLIES);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 236 "input.l"
{yylval.lineno = yylineno; return(TOK_IFF);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 237 "input.l"
{yylval.lineno = yylineno; return(TOK_OR);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 238 "input.l"
{yylval.lineno = yylineno; return(TOK_AND);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 239 "input.l"
{yylval.lineno = yylineno; return(TOK_XOR);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 240 "input.l"
{yylval.lineno = yylineno; return(TOK_XNOR);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 241 "input.l"
{yylval.lineno = yylineno; return(TOK_NOT);}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 243 "input.l"
{yylval.lineno = yylineno; return(TOK_COMMA);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 244 "input.l"
{yylval.lineno = yylineno; return(TOK_COLON);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 245 "input.l"
{yylval.lineno = yylineno; return(TOK_SEMI);}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 246 "input.l"
{yylval.lineno = yylineno; return(TOK_CONCATENATION);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 247 "input.l"
{yylval.lineno = yylineno; return(TOK_PRED);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 248 "input.l"
{yylval.lineno = yylineno; return(TOK_PREDSLIST);}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 249 "input.l"
{yylval.lineno = yylineno; return(TOK_MIRROR);}
	YY_BREAK
/* word constants */
case 127:
YY_RULE_SETUP
#line 252 "input.l"
{
                 char* errorString;
                 WordNumber_ptr wordConstant
		        = WordNumber_from_parsed_string(yytext, &errorString);
                 /* check for errors */
                 if (WORD_NUMBER(NULL) == wordConstant) rpterr(errorString);

                 yylval.node = new_node(NUMBER_WORD,(node_ptr)wordConstant,Nil);
                 return(TOK_NUMBER_WORD);
               }
	YY_BREAK
/* real, fractional and exponential constants */
case 128:
YY_RULE_SETUP
#line 264 "input.l"
{ 
                  yylval.node = new_node(NUMBER_FRAC,
					 (node_ptr)find_string(yytext),Nil);
                  return(TOK_NUMBER_FRAC);
                 }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 270 "input.l"
{ 
                  yylval.node = new_node(NUMBER_EXP,
					 (node_ptr)find_string(yytext),Nil);
                  return(TOK_NUMBER_EXP);
                 }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 276 "input.l"
{ 
                  if (parser_parse_real()) {
                    yylval.node = new_node(NUMBER_REAL,
                                           (node_ptr)find_string(yytext),Nil);
                    return(TOK_NUMBER_REAL);
                  }
                  else {
                    REJECT;
                  }
                 }
	YY_BREAK
/* integer number */
case 131:
YY_RULE_SETUP
#line 288 "input.l"
{
                  int i;
                  sscanf(yytext,"%d",&i);
                  yylval.node = new_node(NUMBER, NODE_FROM_INT(i), Nil);
                  return(TOK_NUMBER);
                 }
	YY_BREAK
/* identifier */
case 132:
YY_RULE_SETUP
#line 296 "input.l"
{ 
                  yylval.node = new_node(ATOM,
					 (node_ptr)find_string(yytext),Nil);
                  return(TOK_ATOM);
                 }
	YY_BREAK
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 301 "input.l"
{
                  yylval.node = new_node(ATOM,(node_ptr)find_string(yytext),Nil);
                  return(TOK_ATOM);
                 } /* Unused token */
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 306 "input.l"
rpterr("illegal character : \"%s\"", yytext);
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 307 "input.l"
ECHO;
	YY_BREAK
#line 1949 "input.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 395 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 395 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 394);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 1;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 307 "input.l"



static int nusmv_skip_comment() {
  register int c;

  do {
    c = input();
  } while ( c != '\n' && c != EOF );
  return(0);
}


